"""Miscellaneous HAL section generators."""


def generate_header() -> str:
    return """; NES2SMS Hardware Abstraction Layer
; Generated by hal_generator.py

.export HAL_StateInit

HAL_StateInit:
    ; Zero all HAL state variables in RAM
    xor  a
    ld   (_ppu_addr_toggle), a
    ld   (_ppu_addr_hi), a
    ld   (_ppu_addr_lo), a
    ld   (_ppu_write_mode), a
    ld   (_ppu_scroll_x), a
    ld   (_ppu_scroll_y), a
    ld   (_ppu_attr_value), a
    ld   (_ppu_chr_data), a
    ld   (_ppu_ctrl_shadow), a
    ld   (_input_strobe), a
    ld   (_input_live_p1), a
    ld   (_input_live_p2), a
    ld   (_input_latch_p1), a
    ld   (_input_latch_p2), a
    ld   (_input_start_p1_pending), a
    ld   (_oam_prio_top), a
    ld   (_oam_prio_bottom), a
    ; Non-zero defaults
    ld   a, %11100000
    ld   (_vdp_reg1_shadow), a
    ld   a, $01
    ld   (_vdp_reg15_shadow), a
    ret
"""


def generate_apu_routines() -> str:
    return """
.export hal_apu_write
.export hal_apu_read

hal_apu_write:
    ; NES APU -> SMS PSG ($7F)
    out ($7f), a
    ret

hal_apu_read:
    sub  a
    ret
"""


def generate_utility_routines() -> str:
    return """
.export hal_vblank_wait

hal_vblank_wait:
-   in   a, ($bf)
    and  $80
    jp   z, -
    ret
"""


def generate_footer() -> str:
    return "\n"
