"""HAL generator for creating Z80 hardware emulation routines."""

from typing import List


class HALGenerator:
    """Generates Z80 assembly for the Hardware Abstraction Layer."""

    def generate_all(self) -> str:
        """Generate the complete HAL library."""
        sections = [
            self.generate_header(),
            self.generate_ppu_routines(),
            self.generate_apu_routines(),
            self.generate_input_routines(),
            self.generate_oam_dma_routine(),
            self.generate_utility_routines(),
            self.generate_footer(),
        ]
        return "\n\n".join(sections)

    def generate_header(self) -> str:
        return """; NES2SMS Hardware Abstraction Layer
; Generated by hal_generator.py
"""

    def generate_ppu_routines(self) -> str:
        return """
.export hal_ppu_write
.export hal_ppu_read

hal_ppu_write:
    ; A = Value to write
    ; L = Register offset (0-7)
    ld   b, a    ; Save value to B
    ld   h, $00
    add  hl, hl  ; hl = offset * 2
    ld   de, _ppu_jump_table
    add  hl, de
    ld   e, (hl)
    inc  hl
    ld   d, (hl)
    ld   a, b    ; Restore value to A
    push de
    ret

_ppu_jump_table:
    .dw _ppu_2000, _ppu_2001, _ppu_2002, _ppu_2003
    .dw _ppu_2004, _ppu_2005, _ppu_2006, _ppu_2007

_ppu_2000: ; PPUCTRL
    ; TODO: Map NES PPUCTRL to SMS VDP regs.
    ; Bits 0-1: Base nametable address ($2000,$2400,$2800,$2C00)
    ; Bit 2: VRAM address increment (0: add 1; 1: add 32)
    ; Bit 3: Sprite pattern table address (0: $0000; 1: $1000)
    ; Bit 4: Background pattern table address (0: $0000; 1: $1000)
    ; Bit 5: Sprite size (0: 8x8; 1: 8x16)
    ; Bit 6: PPU master/slave select
    ; Bit 7: Generate NMI
    ld   (nes_ppu_ctrl), a
    ret

_ppu_2005: ; PPUSCROLL
    ; TODO: Map NES scroll semantics to SMS VDP regs 8/9.
    ret

_ppu_2006: ; PPUADDR
    ; NES PPUADDR is a two-write latch to set VRAM address.
    ld   a, (nes_ppu_latch)
    xor  1
    ld   (nes_ppu_latch), a
    jr   z, .low_byte

.high_byte:
    ld   a, b
    ld   (nes_ppu_addr + 1), a
    ret

.low_byte:
    ld   a, b
    ld   (nes_ppu_addr), a

    ; Map and set VDP address
    ld   hl, (nes_ppu_addr)
    call hal_vdp_map_address
    call VDP_SetWriteAddress
    ret

_ppu_2007: ; PPUDATA
    ; Write value in A to VDP data port
    out  ($BE), a

    ; Auto-increment address
    ld   hl, (nes_ppu_addr)
    ld   a, (nes_ppu_ctrl)
    and  %00000100
    jr   nz, .inc32
    inc  hl
    jr   .update_addr
.inc32:
    ld   de, 32
    add  hl, de
.update_addr:
    ld   (nes_ppu_addr), hl

    ; If we incremented by 32, we MUST re-set the VDP address
    ; because SMS VDP auto-increment is always 1.
    ld   a, (nes_ppu_ctrl)
    and  %00000100
    ret  z

    ld   hl, (nes_ppu_addr)
    call hal_vdp_map_address
    call VDP_SetWriteAddress
    ret

hal_vdp_map_address:
    ; HL = NES address
    ; Returns HL = SMS address + Command bits

    ; Check for Palette ($3F00-$3F1F)
    ld   a, h
    cp   $3F
    jr   nz, .not_palette

    ; Palette: SMS CRAM is accessed at $C000 | offset
    ld   a, l
    and  $1F
    ld   l, a
    ld   h, $C0
    ret

.not_palette:
    ; Check for Nametables ($2000-$2FFF)
    ld   a, h
    and  $F0
    cp   $20
    jr   nz, .not_nametable

    ; Nametable: Map to SMS Nametable at $3800
    ld   a, h
    sub  $20
    and  $07
    add  a, $38
    ld   h, a
    ret

.not_nametable:
    ; Default: direct mapping for patterns etc.
    ld   a, h
    and  $3F
    ld   h, a
    ret

_ppu_2001: ; PPUMASK
    ret

_ppu_2002: ; PPUSTATUS
    ; Reading PPUSTATUS resets the PPUADDR latch
    xor  a
    ld   (nes_ppu_latch), a
    ; Return dummy status for now (bit 7 = vblank)
    in   a, ($BF)
    and  $80
    ret

_ppu_2003: ; OAMADDR
_ppu_2004: ; OAMDATA
    ret

hal_ppu_read:
    ; L = Register offset (0-7)
    ld   h, $00
    add  hl, hl  ; hl = offset * 2
    ld   de, _ppu_read_jump_table
    add  hl, de
    ld   e, (hl)
    inc  hl
    ld   d, (hl)
    push de
    ret

_ppu_read_jump_table:
    .dw _ppu_read_dead, _ppu_read_dead, _ppu_2002, _ppu_read_dead
    .dw _ppu_read_dead, _ppu_read_dead, _ppu_read_dead, _ppu_read_2007

_ppu_read_dead:
    xor  a
    ret

_ppu_read_2007:
    ld   a, (nes_ppu_read_buffer)
    ld   b, a ; save buffer to return

    in   a, ($BE)
    ld   (nes_ppu_read_buffer), a

    ; Auto-increment address
    push bc
    ld   hl, (nes_ppu_addr)
    ld   a, (nes_ppu_ctrl)
    and  %00000100
    jr   nz, .read_inc32
    inc  hl
    jr   .read_update_addr
.read_inc32:
    ld   de, 32
    add  hl, de
.read_update_addr:
    ld   (nes_ppu_addr), hl

    ; If we incremented by 32, we MUST re-set the VDP address
    ld   a, (nes_ppu_ctrl)
    and  %00000100
    jr   z, .read_done

    ld   hl, (nes_ppu_addr)
    call hal_vdp_map_address
    call VDP_SetWriteAddress
.read_done:
    pop  bc
    ld   a, b ; return previous buffer
    ret
"""

    def generate_apu_routines(self) -> str:
        return """
.export hal_apu_write
.export hal_apu_read

hal_apu_write:
    ; NES APU -> SMS PSG ($7F)
    out ($7f), a
    ret

hal_apu_read:
    sub  a
    ret
"""

    def generate_input_routines(self) -> str:
        return """
.export hal_input_write
.export hal_input_read

hal_input_write:
    ; A = Value
    ; L = Port (0 or 1)
    ; TODO: Implement latching logic
    RET

hal_input_read:
    ; L = Port (0 or 1)
    ; Returns A = Serialized button bits
    ; Reads from SMS Ports $DC/$DD
    RET
"""

    def generate_oam_dma_routine(self) -> str:
        return """
.export hal_oam_dma

hal_oam_dma:
    ; A = Page high byte (e.g., $02 for $0200)
    ; Copies 256 bytes from (A:00) to VDP SAT (Sprite Attribute Table)
    LD   h, a
    LD   l, $00
    ; TODO: Bulk copy to VDP
    RET
"""

    def generate_utility_routines(self) -> str:
        return """
.export hal_vblank_wait

hal_vblank_wait:
-   in   a, ($bf)
    and  $80
    jp   z, -
    ret

.section "HAL_Variables" ramfree
nes_ppu_latch:       .db
nes_ppu_addr:        .dw
nes_ppu_ctrl:        .db
nes_ppu_read_buffer: .db
.ends
"""

    def generate_footer(self) -> str:
        return "\n"
