"""HAL generator for creating Z80 hardware emulation routines."""

from typing import List


class HALGenerator:
    """Generates Z80 assembly for the Hardware Abstraction Layer."""

    def __init__(self, split_y: int = 48):
        # Split point used by the 2-zone sprite-priority policy.
        self.split_y = max(0, min(239, int(split_y)))

    def generate_all(self) -> str:
        """Generate the complete HAL library."""
        sections = [
            self.generate_header(),
            self.generate_ppu_routines(),
            self.generate_apu_routines(),
            self.generate_input_routines(),
            self.generate_oam_dma_routine(),
            self.generate_utility_routines(),
            self.generate_footer(),
        ]
        return "\n\n".join(sections)

    def generate_header(self) -> str:
        return """; NES2SMS Hardware Abstraction Layer
; Generated by hal_generator.py

.export HAL_StateInit

HAL_StateInit:
    ; Zero all HAL state variables in RAM
    xor  a
    ld   (_ppu_addr_toggle), a
    ld   (_ppu_addr_hi), a
    ld   (_ppu_addr_lo), a
    ld   (_ppu_write_mode), a
    ld   (_ppu_scroll_x), a
    ld   (_ppu_scroll_y), a
    ld   (_ppu_attr_value), a
    ld   (_ppu_chr_data), a
    ld   (_ppu_ctrl_shadow), a
    ld   (_input_strobe), a
    ld   (_input_live_p1), a
    ld   (_input_live_p2), a
    ld   (_input_latch_p1), a
    ld   (_input_latch_p2), a
    ld   (_input_start_p1_pending), a
    ld   (_oam_prio_top), a
    ld   (_oam_prio_bottom), a
    ; Non-zero defaults
    ld   a, %11100000
    ld   (_vdp_reg1_shadow), a
    ld   a, $01
    ld   (_vdp_reg15_shadow), a
    ret
"""

    def generate_ppu_routines(self) -> str:
        return """
.export hal_ppu_write
.export hal_ppu_read

hal_ppu_write:
    ; A = Value to write
    ; L = Register offset (0-7)
    ld   h, $00
    add  hl, hl  ; hl = offset * 2
    ld   de, _ppu_jump_table
    add  hl, de
    ld   e, (hl)
    inc  hl
    ld   d, (hl)
    push de
    ret

_ppu_jump_table:
    .dw _ppu_2000, _ppu_2001, _ppu_2002, _ppu_2003
    .dw _ppu_2004, _ppu_2005, _ppu_2006, _ppu_2007

_ppu_2000: ; PPUCTRL
    ld   (_ppu_ctrl_shadow), a
    ; Bit 7 = NES NMI enable → SMS VDP reg 1 bit 5 (frame IRQ enable)
    push bc
    ld   b, a
    ld   a, (_vdp_reg1_shadow)
    bit  7, b
    jr   nz, _ppu_2000_nmi_on
    res  5, a
    jr   _ppu_2000_done
_ppu_2000_nmi_on:
    set  5, a
_ppu_2000_done:
    ld   (_vdp_reg1_shadow), a
    ld   b, a
    ld   a, 1
    call VDP_WriteReg
    pop  bc
    ret

_ppu_2005: ; PPUSCROLL
    ; PPUSCROLL uses the same first/second write latch as PPUADDR.
    ; 1st write = X scroll, 2nd write = Y scroll.
    push bc
    ld   b, a
    ld   a, (_ppu_addr_toggle)
    or   a
    jr   nz, _ppu_2005_y
    ; First write: X scroll (invert to match SMS horizontal direction)
    ld   a, b
    ld   (_ppu_scroll_x), a
    cpl
    inc  a
    ld   b, a
    ld   a, 8
    call VDP_WriteReg
    ld   a, $01
    ld   (_ppu_addr_toggle), a
    pop  bc
    ret
_ppu_2005_y:
    ; Second write: Y scroll
    ld   a, b
    ld   (_ppu_scroll_y), a
    ld   b, a
    ld   a, 9
    call VDP_WriteReg
    xor  a
    ld   (_ppu_addr_toggle), a
    pop  bc
    ret

_ppu_2006: ; PPUADDR
    push bc
    ld   b, a
    ld   a, (_ppu_addr_toggle)
    or   a
    jr   nz, _ppu_2006_lo
    ; First write: high byte
    ld   a, b
    ld   (_ppu_addr_hi), a
    ; Enter neutral mode until low byte resolves target range.
    xor  a
    ld   (_ppu_write_mode), a
    ld   a, $01
    ld   (_ppu_addr_toggle), a
    pop  bc
    ret
_ppu_2006_lo:
    ; Second write: low byte
    ld   a, b
    ld   (_ppu_addr_lo), a
    xor  a
    ld   (_ppu_addr_toggle), a
    ; Set up VDP write address based on NES PPU address range
    ld   a, (_ppu_addr_hi)
    cp   $3F
    jr   z, _ppu_2006_palette
    cp   $20
    jr   c, _ppu_2006_chr
    ; Attribute table ranges ($23C0/$27C0/$2BC0/$2FC0) are translated to
    ; SMS name table attribute bytes by _ppu_2007_attribute.
    ld   a, (_ppu_addr_hi)
    and  $03
    cp   $03
    jr   nz, _ppu_2006_nametable
    ld   a, (_ppu_addr_lo)
    cp   $C0
    jr   nc, _ppu_2006_attribute
_ppu_2006_nametable:
    ; Ensure VDP auto-increment = 2 so each tile write advances one SMS cell.
    ld   a, $02
    call _ppu_set_vdp_increment

    ; Nametable range $20xx-$2Fxx -> SMS $3800 + offset
    ; NES addr = ($2000 + offset), SMS addr = ($3800 + offset*2)
    ; For simplicity, set VDP address for nametable writes
    sub  $20
    ld   d, a
    ld   a, (_ppu_addr_lo)
    ld   e, a
    ; DE = NES nametable offset (from $2000)
    ; SMS nametable at $3800, each entry = 2 bytes
    ; SMS addr = $3800 + (DE * 2)
    sla  e
    rl   d
    ld   a, d
    add  a, $38
    ld   d, a
    ; Set VDP write address
    ld   a, e
    out  ($BF), a
    ld   a, d
    or   $40
    out  ($BF), a
    ld   a, $01
    ld   (_ppu_write_mode), a  ; nametable mode
    pop  bc
    ret
_ppu_2006_attribute:
    ld   a, $01
    call _ppu_set_vdp_increment
    ld   a, $03
    ld   (_ppu_write_mode), a  ; attribute table mode
    pop  bc
    ret
_ppu_2006_palette:
    ; Palette writes use byte-wise VDP increment.
    ld   a, $01
    call _ppu_set_vdp_increment
    ; Palette $3F00-$3F1F -> SMS CRAM
    ld   a, (_ppu_addr_lo)
    and  $1F
    ld   e, a
    ld   d, $00
    ; SMS CRAM address = $C000 + offset
    ld   a, e
    out  ($BF), a
    ld   a, $C0
    out  ($BF), a
    ld   a, $02
    ld   (_ppu_write_mode), a  ; palette mode
    pop  bc
    ret
_ppu_2006_chr:
    ; CHR/pattern range $0000-$1FFF
    ; Handle runtime CHR-RAM writes by mapping NES bitplanes to SMS tile planes 0/1.
    ld   a, $01
    call _ppu_set_vdp_increment
    ld   a, $04
    ld   (_ppu_write_mode), a
    pop  bc
    ret

_ppu_2007: ; PPUDATA
    push bc
    push de
    push hl
    ld   b, a
    ld   a, (_ppu_write_mode)
    cp   $02
    jp   z, _ppu_2007_palette
    cp   $03
    jp   z, _ppu_2007_attribute
    cp   $04
    jp   z, _ppu_2007_chr
    cp   $01
    jp   z, _ppu_2007_nametable
    ; Unsupported mode: ignore
    call _ppu_advance_vram_addr
    pop  hl
    pop  de
    pop  bc
    ret
_ppu_2007_palette:
    ; A(saved in B) = NES palette index (0-63)
    ; Convert to SMS color via lookup table
    ld   a, b
    and  $3F
    ld   e, a
    ld   d, $00
    ld   hl, _nes_to_sms_color
    add  hl, de
    ld   a, (hl)
    out  ($BE), a
    call _ppu_advance_vram_addr
    pop  hl
    pop  de
    pop  bc
    ret
_ppu_2007_nametable:
    ; With VDP increment=2, writing only the tile byte updates one SMS cell.
    ; Attribute bytes remain zero (set during clear/init).
    ld   a, b
    out  ($BE), a
    call _ppu_advance_vram_addr
    pop  hl
    pop  de
    pop  bc
    ret
_ppu_2007_attribute:
    ; Expand NES attribute byte into SMS palette bit (entry bit 3) for each 2x2 tile block.
    ; Mapping policy: NES palettes 0/1 -> SMS palette 0, NES palettes 2/3 -> SMS palette 1.
    ld   a, b
    ld   (_ppu_attr_value), a
    ; Compute base nametable entry index from current PPU attribute address.
    ; nametable index (0..3)
    ld   a, (_ppu_addr_hi)
    sub  $20
    and  $0C
    rrca
    rrca
    ld   h, a
    ; attribute index inside table (0..63)
    ld   a, (_ppu_addr_lo)
    and  $3F
    ld   l, a

    ; DE = attr_y*128
    ld   a, l
    and  $38
    ld   e, a
    ld   d, $00
    sla  e
    rl   d
    sla  e
    rl   d
    sla  e
    rl   d
    sla  e
    rl   d
    ; + attr_x*4
    ld   a, l
    and  $07
    add  a, a
    add  a, a
    add  a, e
    ld   e, a
    jr   nc, _ppu_attr_no_xy_carry
    inc  d
_ppu_attr_no_xy_carry:
    ; + nametable*0x400
    ld   a, h
    ld   c, a
    ld   b, $00
    sla  c
    rl   b
    sla  c
    rl   b
    sla  c
    rl   b
    sla  c
    rl   b
    sla  c
    rl   b
    sla  c
    rl   b
    sla  c
    rl   b
    sla  c
    rl   b
    sla  c
    rl   b
    sla  c
    rl   b
    ld   a, e
    add  a, c
    ld   e, a
    ld   a, d
    adc  a, b
    ld   d, a
    ; Convert entry index to VRAM address of attribute byte:
    ; $3800 + entry*2 + 1
    sla  e
    rl   d
    ld   a, e
    add  a, $01
    ld   e, a
    ld   a, d
    adc  a, $38
    ld   d, a
    ; Keep top-left base in HL for quadrant offsets.
    ld   h, d
    ld   l, e

    ; Top-left quadrant (bits 1:0 -> use bit 1 as SMS palette selector)
    ld   a, (_ppu_attr_value)
    and  $02
    sla  a
    sla  a
    call _ppu_attr_write_2x2

    ; Top-right quadrant (bits 3:2 -> use bit 3)
    ld   bc, $0004
    add  hl, bc
    ld   d, h
    ld   e, l
    ld   a, (_ppu_attr_value)
    and  $08
    call _ppu_attr_write_2x2

    ; Bottom-left quadrant (bits 5:4 -> use bit 5)
    ld   bc, $007C
    add  hl, bc
    ld   d, h
    ld   e, l
    ld   a, (_ppu_attr_value)
    and  $20
    srl  a
    srl  a
    call _ppu_attr_write_2x2

    ; Bottom-right quadrant (bits 7:6 -> use bit 7)
    ld   bc, $0004
    add  hl, bc
    ld   d, h
    ld   e, l
    ld   a, (_ppu_attr_value)
    and  $80
    srl  a
    srl  a
    srl  a
    srl  a
    call _ppu_attr_write_2x2

    call _ppu_advance_vram_addr
    pop  hl
    pop  de
    pop  bc
    ret
_ppu_2007_chr:
    ; Runtime CHR write: map NES tile bitplanes directly into SMS tile plane bytes.
    ; NES byte offset inside tile determines destination row/plane.
    ld   a, b
    ld   (_ppu_chr_data), a

    ; DE = current NES PPU address (13-bit in $0000-$1FFF)
    ld   a, (_ppu_addr_hi)
    and  $1F
    ld   d, a
    ld   a, (_ppu_addr_lo)
    ld   e, a

    ; C = byte offset inside tile (0..15)
    ld   a, e
    and  $0F
    ld   c, a

    ; DE = tile index (address >> 4)
    srl  d
    rr   e
    srl  d
    rr   e
    srl  d
    rr   e
    srl  d
    rr   e

    ; B = destination plane (0 or 1), C = row (0..7)
    ld   a, c
    cp   $08
    jr   c, _ppu_chr_plane0
    sub  $08
    ld   c, a
    ld   b, $01
    jr   _ppu_chr_plane_done
_ppu_chr_plane0:
    ld   c, a
    ld   b, $00
_ppu_chr_plane_done:
    ; DE = tile_index * 32
    sla  e
    rl   d
    sla  e
    rl   d
    sla  e
    rl   d
    sla  e
    rl   d
    sla  e
    rl   d

    ; + row * 4
    ld   a, c
    add  a, a
    add  a, a
    add  a, e
    ld   e, a
    jr   nc, _ppu_chr_no_row_carry
    inc  d
_ppu_chr_no_row_carry:
    ; + plane
    ld   a, e
    add  a, b
    ld   e, a
    jr   nc, _ppu_chr_no_plane_carry
    inc  d
_ppu_chr_no_plane_carry:
    ; Write one byte to computed SMS VRAM address
    ld   a, e
    out  ($BF), a
    ld   a, d
    or   $40
    out  ($BF), a
    ld   a, (_ppu_chr_data)
    out  ($BE), a

    call _ppu_advance_vram_addr
    pop  hl
    pop  de
    pop  bc
    ret

_ppu_2001: ; PPUMASK
    ; Bits 3,4 = show BG, show sprites
    ; Map to VDP register 1 bit 6 (display enable)
    push bc
    ld   b, a
    ld   a, (_vdp_reg1_shadow)
    bit  3, b
    jr   nz, _ppu_2001_on
    bit  4, b
    jr   nz, _ppu_2001_on
    ; Display off
    res  6, a
    jr   _ppu_2001_write
_ppu_2001_on:
    set  6, a
_ppu_2001_write:
    ld   (_vdp_reg1_shadow), a
    ld   b, a
    ld   a, 1
    call VDP_WriteReg
    pop  bc
    ret

_ppu_2002: ; PPUSTATUS
_ppu_2003: ; OAMADDR
_ppu_2004: ; OAMDATA
    ret

hal_ppu_read:
    ; L = register offset
    ld   a, l
    cp   2
    jr   z, _ppu_read_status
    xor  a
    ret
_ppu_read_status:
    ; Reading $2002 resets the address latch toggle
    xor  a
    ld   (_ppu_addr_toggle), a
    ; Return VDP status (bit 7 = vblank)
    in   a, ($BF)
    ret

; PPU state variables are absolute WRAM labels from memory.inc (.ENUM $C000)

_ppu_advance_vram_addr:
    ; Emulate NES internal VRAM increment after each PPUDATA write.
    ; PPUCTRL bit 2 selects increment of 1 (clear) or 32 (set).
    ld   a, (_ppu_ctrl_shadow)
    and  $04
    jr   z, _ppu_addr_inc1
    ld   a, (_ppu_addr_lo)
    add  a, $20
    ld   (_ppu_addr_lo), a
    ret  nc
    ld   a, (_ppu_addr_hi)
    adc  a, $00
    ld   (_ppu_addr_hi), a
    ret
_ppu_addr_inc1:
    ld   a, (_ppu_addr_lo)
    inc  a
    ld   (_ppu_addr_lo), a
    ret  nz
    ld   a, (_ppu_addr_hi)
    inc  a
    ld   (_ppu_addr_hi), a
    ret

_ppu_attr_write_2x2:
    ; A = attribute byte to write (bit3 palette select)
    ; DE = top-left attribute byte address for 2x2 tiles
    ld   b, a
    ld   a, b
    call _ppu_attr_write_cell
    inc  de
    inc  de
    ld   a, b
    call _ppu_attr_write_cell
    ld   h, d
    ld   l, e
    ld   bc, $003E
    add  hl, bc
    ld   d, h
    ld   e, l
    ld   a, b
    call _ppu_attr_write_cell
    inc  de
    inc  de
    ld   a, b
    call _ppu_attr_write_cell
    ret

_ppu_attr_write_cell:
    push af
    ld   a, e
    out  ($BF), a
    ld   a, d
    or   $40
    out  ($BF), a
    pop  af
    out  ($BE), a
    ret

_ppu_set_vdp_increment:
    ; A = desired increment value for VDP register 15.
    ld   c, a
    ld   a, (_vdp_reg15_shadow)
    cp   c
    ret  z
    ld   a, c
    ld   (_vdp_reg15_shadow), a
    push bc
    ld   b, a
    ld   a, 15
    call VDP_WriteReg
    pop  bc
    ret

; NES palette index (0-63) -> SMS color (--BBGGRR)
_nes_to_sms_color:
    ;      0     1     2     3     4     5     6     7     8     9     A     B     C     D     E     F
    .db $15, $02, $06, $0A, $09, $08, $08, $04, $14, $10, $10, $11, $15, $00, $00, $00  ; $00-$0F
    .db $3F, $07, $0B, $2E, $2D, $0D, $1C, $2C, $28, $24, $20, $21, $25, $00, $00, $00  ; $10-$1F
    .db $3F, $0B, $0F, $2F, $2F, $1F, $3D, $3D, $3C, $38, $34, $35, $3A, $15, $00, $00  ; $20-$2F
    .db $3F, $2F, $2F, $3F, $3F, $2B, $3F, $3F, $3E, $3D, $39, $3A, $3F, $2A, $00, $00  ; $30-$3F
"""

    def generate_apu_routines(self) -> str:
        return """
.export hal_apu_write
.export hal_apu_read

hal_apu_write:
    ; NES APU -> SMS PSG ($7F)
    out ($7f), a
    ret

hal_apu_read:
    sub  a
    ret
"""

    def generate_input_routines(self) -> str:
        return """
.export hal_input_write
.export hal_input_read
.export hal_input_on_pause_nmi

hal_input_write:
    ; A = Value (bit0=strobe), L = Port (0 or 1)
    ; NES behavior:
    ; - $4016 bit0 controls strobe/latch for BOTH controllers.
    ; - $4017 writes are ignored by input latch logic.
    ; strobe=1: reads return current A button (no shift)
    ; strobe=0: reads shift serialized latch
    push bc
    ld   c, a
    ld   a, l
    or   a
    jr   nz, _input_write_ignore_p2

    ; Port 0 ($4016) controls shared strobe
    ld   a, (_input_strobe)
    ld   b, a                    ; previous strobe
    ld   a, c
    and  $01
    ld   (_input_strobe), a
    or   a
    jr   z, _input_write_low
    ; Strobe high: keep live A reads current for both pads.
    call _input_capture_p1
    call _input_capture_p2
    jr   _input_write_done
_input_write_low:
    ; Latch once on high->low transition.
    ld   a, b
    or   a
    jr   z, _input_write_done
    call _input_capture_p1
    call _input_capture_p2
    jr   _input_write_done
_input_write_ignore_p2:
    ; Port 1 ($4017) frame counter is not part of joypad strobe.
    jr   _input_write_done
_input_write_done:
    pop  bc
    ret

hal_input_on_pause_nmi:
    ; SMS PAUSE/NMI maps to NES Start pulse for next P1 latch.
    ld   a, $01
    ld   (_input_start_p1_pending), a
    ret

_input_capture_p1:
    call _input_read_sms_p1
    call _map_sms_to_nes
    ld   b, a
    ld   a, (_input_start_p1_pending)
    or   a
    jr   z, _input_capture_p1_no_start
    ld   a, b
    set  3, a                    ; NES Start
    ld   b, a
    xor  a
    ld   (_input_start_p1_pending), a
_input_capture_p1_no_start:
    ld   a, b
    ld   (_input_live_p1), a
    ld   (_input_latch_p1), a
    ret

_input_capture_p2:
    call _input_read_sms_p2
    call _map_sms_to_nes
    ld   (_input_live_p2), a
    ld   (_input_latch_p2), a
    ret

_input_read_sms_p1:
    in   a, ($DC)
    cpl
    and  $3F
    ret

_input_read_sms_p2:
    ; P2 on SMS is split across ports:
    ; - $DC bit6=Up, bit7=Down
    ; - $DD bit0=Left, bit1=Right, bit2=Button1, bit3=Button2
    ; Output A normalized to SMS internal format:
    ;   Up=b0,Down=b1,Left=b2,Right=b3,Btn1=b4,Btn2=b5
    push bc
    in   a, ($DC)
    cpl
    and  $C0
    ld   b, a
    in   a, ($DD)
    cpl
    and  $0F
    ld   c, a
    xor  a
    bit  6, b
    jr   z, +
    set  0, a
+:  bit  7, b
    jr   z, +
    set  1, a
+:  bit  0, c
    jr   z, +
    set  2, a
+:  bit  1, c
    jr   z, +
    set  3, a
+:  bit  2, c
    jr   z, +
    set  4, a
+:  bit  3, c
    jr   z, +
    set  5, a
+:  pop  bc
    ret

_map_sms_to_nes:
    ; Input A: SMS format (Up=b0,Down=b1,Left=b2,Right=b3,Btn1=b4,Btn2=b5)
    ; Output A: NES serial order (A=b0,B=b1,Sel=b2,Start=b3,Up=b4,Down=b5,Left=b6,Right=b7)
    push bc
    ld   b, a
    xor  a
    bit  4, b
    jr   z, +
    set  0, a
+:  bit  5, b
    jr   z, +
    set  1, a
+:  bit  4, b
    jr   z, +
    bit  5, b
    jr   z, +
    set  2, a                    ; Select = BTN1+BTN2
+:  bit  0, b
    jr   z, +
    set  4, a
+:  bit  1, b
    jr   z, +
    set  5, a
+:  bit  2, b
    jr   z, +
    set  6, a
+:  bit  3, b
    jr   z, +
    set  7, a
+:  pop  bc
    ret

hal_input_read:
    ; L = Port (0 or 1)
    ; Returns bit 0 = current button state (NES serial style)
    ; strobe=1: returns current A (no shift)
    ; strobe=0: shifts latch right, filling bit 7 with 1
    push bc
    ld   a, l
    or   a
    jr   nz, _read_p2
    ld   a, (_input_strobe)
    or   a
    jr   z, _read_p1_shift
    call _input_capture_p1
    ld   a, (_input_live_p1)
    and  $01
    jr   _input_read_done
_read_p1_shift:
    ld   a, (_input_latch_p1)
    ld   b, a
    srl  a
    set  7, a
    ld   (_input_latch_p1), a
    ld   a, b
    and  $01
    jr   _input_read_done
_read_p2:
    ld   a, (_input_strobe)
    or   a
    jr   z, _read_p2_shift
    call _input_capture_p2
    ld   a, (_input_live_p2)
    and  $01
    jr   _input_read_done
_read_p2_shift:
    ld   a, (_input_latch_p2)
    ld   b, a
    srl  a
    set  7, a
    ld   (_input_latch_p2), a
    ld   a, b
    and  $01
_input_read_done:
    pop  bc
    ret

; Input state variables are absolute WRAM labels from memory.inc (.ENUM $C000)
"""

    def generate_oam_dma_routine(self) -> str:
        return f"""
.export hal_oam_dma

hal_oam_dma:
    ; A = NES page number (e.g., $02 for $0200)
    ; Relocated to SMS RAM ($C0+page) automatically
    ; Uploads to SMS VDP SAT at $3F00
    push bc
    push de
    push hl

    add  a, $C0       ; Relocate NES page to SMS RAM
    ld   h, a
    ld   l, $00       ; HL = source page in SMS RAM
    xor  a
    ld   (_oam_prio_top), a
    ld   (_oam_prio_bottom), a

    ; --- First pass: write Y positions to SAT $3F00 ---
    push hl
    ld   a, $00
    out  ($BF), a
    ld   a, $7F       ; $3F00 | $40 (VDP write flag)
    out  ($BF), a

    ld   b, 64
_oam_y_loop:
    ld   a, (hl)      ; NES Y position (offset +0)
    inc  a            ; SMS Y is effectively one scanline lower
    out  ($BE), a
    inc  hl
    inc  hl
    inc  hl
    inc  hl            ; skip 4 bytes to next sprite
    djnz _oam_y_loop

    ; --- Second pass: write X/tile pairs to SAT $3F80 ---
    pop  hl
    ld   a, $80
    out  ($BF), a
    ld   a, $7F       ; $3F80 | $40 (VDP write flag)
    out  ($BF), a

    ld   b, 64
_oam_xt_loop:
    ld   a, (hl)      ; NES Y position (offset +0)
    ld   c, a
    inc  hl            ; tile offset +1
    ld   a, (hl)      ; NES tile index
    ld   d, a
    inc  hl            ; attributes offset +2
    ld   a, (hl)
    ld   e, a
    bit  5, e
    jr   z, _oam_prio_done
    ld   a, c
    cp   {self.split_y}
    jr   c, _oam_prio_mark_top
    ld   a, $01
    ld   (_oam_prio_bottom), a
    jr   _oam_prio_done
_oam_prio_mark_top:
    ld   a, $01
    ld   (_oam_prio_top), a
_oam_prio_done:
    inc  hl            ; X offset +3
    ld   a, (hl)      ; NES X position (offset +3)
    out  ($BE), a      ; write X
    push hl
    call _oam_map_variant_tile
    out  ($BE), a      ; write tile
    pop  hl
    inc  hl            ; advance to next sprite
    djnz _oam_xt_loop

    pop  hl
    pop  de
    pop  bc
    ret

_oam_map_variant_tile:
    ; D = base tile, E = NES attributes
    ; combo nibble: [V][H][P1][P0]
    ld   a, e
    and  $03
    ld   c, a
    bit  6, e
    jr   z, _oam_combo_h_done
    set  2, c
_oam_combo_h_done:
    bit  7, e
    jr   z, _oam_combo_ready
    set  3, c
_oam_combo_ready:
    ; HL = (D * 16) + C
    ld   a, d
    and  $0F
    add  a, a
    add  a, a
    add  a, a
    add  a, a
    ld   l, a
    ld   a, d
    and  $F0
    rrca
    rrca
    rrca
    rrca
    ld   h, a
    ld   a, l
    add  a, c
    ld   l, a
    jr   nc, _oam_lookup_ready
    inc  h
_oam_lookup_ready:
    ld   de, SpriteVariantMap
    add  hl, de
    ld   a, (hl)
    ret

; OAM state variables are absolute WRAM labels from memory.inc (.ENUM $C000)
"""

    def generate_utility_routines(self) -> str:
        return """
.export hal_vblank_wait

hal_vblank_wait:
-   in   a, ($bf)
    and  $80
    jp   z, -
    ret
"""

    def generate_footer(self) -> str:
        return "\n"
