"""HAL generator for creating Z80 hardware emulation routines."""

from typing import List


class HALGenerator:
    """Generates Z80 assembly for the Hardware Abstraction Layer."""

    def generate_all(self) -> str:
        """Generate the complete HAL library."""
        sections = [
            self.generate_header(),
            self.generate_ppu_routines(),
            self.generate_apu_routines(),
            self.generate_input_routines(),
            self.generate_oam_dma_routine(),
            self.generate_utility_routines(),
            self.generate_footer(),
        ]
        return "\n\n".join(sections)

    def generate_header(self) -> str:
        return """; NES2SMS Hardware Abstraction Layer
; Generated by hal_generator.py
"""

    def generate_ppu_routines(self) -> str:
        return """
.export hal_ppu_write
.export hal_ppu_read

hal_ppu_write:
    ; A = Value to write
    ; L = Register offset (0-7)
    ld   h, $00
    add  hl, hl  ; hl = offset * 2
    ld   de, _ppu_jump_table
    add  hl, de
    ld   e, (hl)
    inc  hl
    ld   d, (hl)
    push de
    ret

_ppu_jump_table:
    .dw _ppu_2000, _ppu_2001, _ppu_2002, _ppu_2003
    .dw _ppu_2004, _ppu_2005, _ppu_2006, _ppu_2007

_ppu_2000: ; PPUCTRL
    ; Keep bootstrap display stable: translated writes are ignored for now.
    ret

_ppu_2005: ; PPUSCROLL
    ; TODO: Map NES scroll semantics to SMS VDP regs 8/9.
    ret

_ppu_2006: ; PPUADDR
    ; TODO: Implement address latch compatibility with NES $2006.
    ret

_ppu_2007: ; PPUDATA
    ; Prevent translated reset code from clobbering bootstrap tilemap.
    ret

_ppu_2001: ; PPUMASK
_ppu_2002: ; PPUSTATUS
_ppu_2003: ; OAMADDR
_ppu_2004: ; OAMDATA
    ret

hal_ppu_read:
    ; Return clear status by default to avoid dead loops on incomplete translation.
    xor  a
    ret
"""

    def generate_apu_routines(self) -> str:
        return """
.export hal_apu_write
.export hal_apu_read

hal_apu_write:
    ; NES APU -> SMS PSG ($7F)
    out ($7f), a
    ret

hal_apu_read:
    sub  a
    ret
"""

    def generate_input_routines(self) -> str:
        return """
.export hal_input_write
.export hal_input_read

hal_input_write:
    ; A = Value
    ; L = Port (0 or 1)
    ; TODO: Implement latching logic
    RET

hal_input_read:
    ; L = Port (0 or 1)
    ; Returns A = Serialized button bits
    ; Reads from SMS Ports $DC/$DD
    RET
"""

    def generate_oam_dma_routine(self) -> str:
        return """
.export hal_oam_dma

hal_oam_dma:
    ; A = Page high byte (e.g., $02 for $0200)
    ; Copies 256 bytes from (A:00) to VDP SAT (Sprite Attribute Table)
    LD   h, a
    LD   l, $00
    ; TODO: Bulk copy to VDP
    RET
"""

    def generate_utility_routines(self) -> str:
        return """
.export hal_vblank_wait

hal_vblank_wait:
-   in   a, ($bf)
    and  $80
    jp   z, -
    ret
"""

    def generate_footer(self) -> str:
        return "\n"
