from . import IHalComponent, Z80ProjectBuilder
import textwrap

class WlaDxInputHal(IHalComponent):
    def get_asm(self) -> str:
        return textwrap.dedent("""; SMS Input HAL (WLA-DX)
        ; Generated by nes2sms/scripts/sms_packer.py
        
        .section \"Input_HAL\" FREE
        
        Input_ReadJoypad1:
            in   a, ($DC)
            cpl
            and  $3F
            ret
            
        .define INPUT_UP    %00000001
        .define INPUT_DOWN  %00000010
        .define INPUT_LEFT  %00000100
        .define INPUT_RIGHT %00001000
        .define INPUT_BTN1  %00010000
        .define INPUT_BTN2  %00100000
        
        .ends
        """)

class WlaDxPsgHal(IHalComponent):
    def get_asm(self) -> str:
        return textwrap.dedent("""; SMS PSG (SN76489) HAL (WLA-DX)
        
        .section \"PSG_HAL\" FREE
        
        PSG_PORT .equ $7F
        
        PSG_Init:
            ld   a, %10011111           ; Tone1: attenuation = 15 (silent)
            out  (PSG_PORT), a
            ld   a, %10111111           ; Tone2: attenuation = 15
            out  (PSG_PORT), a
            ld   a, %11011111           ; Tone3: attenuation = 15
            out  (PSG_PORT), a
            ld   a, %11111111           ; Noise: attenuation = 15
            out  (PSG_PORT), a
            ret
            
        ; PSG_SetTone: DE = channel latch (0=T1,1=T2,2=T3), HL = period (10-bit)
        PSG_SetTone:
            ld   a, h
            and  $03
            ld   a, l
            and  $0F
            ld   b, a
            ld   a, d
            rlca \\ rlca \\ rlca \\ rlca \\ rlca
            or   %10000000
            or   b
            out  (PSG_PORT), a
            ld   a, l
            rlca \\ rlca \\ rlca \\ rlca
            or   h
            and  $3F
            out  (PSG_PORT), a
            ret
            
        ; PSG_SetVolume: D = channel (0–3), E = attenuation (0=loud, 15=silent)
        PSG_SetVolume:
            ld   a, d
            rlca \\ rlca \\ rlca \\ rlca \\ rlca
            or   %10010000
            ld   b, a
            ld   a, e
            and  $0F
            or   b
            out  (PSG_PORT), a
            ret
            
        .ends
        """)

class WlaDxMapperHal(IHalComponent):
    def get_asm(self) -> str:
        return textwrap.dedent("""; SMS Sega Mapper HAL (WLA-DX)
        
        .section \"Mapper_HAL\" FREE
        
        Mapper_Init:
            ld   a, 0
            ld   ($FFFD), a
            ld   a, 1
            ld   ($FFFE), a
            ld   a, 2
            ld   ($FFFF), a
            ret
            
        Mapper_SetSlot1:
            ld   ($FFFE), a
            ret
            
        Mapper_SetSlot2:
            ld   ($FFFF), a
            ret
            
        .ends
        """)
