@echo off
REM Build script for Windows
REM Generated by nes2sms

setlocal
set "WLA_DIR=%~dp0tools\wla-dx"
if not exist "%WLA_DIR%\wla-z80.exe" set "WLA_DIR=%~dp0..\tools\wla-dx"
if not exist "%WLA_DIR%\wla-z80.exe" set "WLA_DIR=%~dp0..\..\tools\wla-dx"
set "PATH=%WLA_DIR%;%PATH%"

cd /d "%~dp0"
if not exist "main.asm" (
    echo [build] ERROR: main.asm not found in %CD%
    goto error
)

echo [build] Building SMS ROM in %CD%...
wla-z80.exe -v -o main.o main.asm
if errorlevel 1 goto error

wla-z80.exe -v -o init.o init.asm
if errorlevel 1 goto error

wla-z80.exe -v -o interrupts.o interrupts.asm
if errorlevel 1 goto error

wla-z80.exe -v -o assets.o assets.asm
if errorlevel 1 goto error

wla-z80.exe -v -o hal\vdp.o hal\vdp.asm
if errorlevel 1 goto error

wla-z80.exe -v -o hal\psg.o hal\psg.asm
if errorlevel 1 goto error

wla-z80.exe -v -o hal\input.o hal\input.asm
if errorlevel 1 goto error

wla-z80.exe -v -o hal\mapper.o hal\mapper.asm
if errorlevel 1 goto error

wla-z80.exe -v -o stubs\game_logic.o stubs\game_logic.asm
if errorlevel 1 goto error

wlalink.exe link.sms game.sms
if errorlevel 1 goto error

if exist game.sms (
    echo [build] SUCCESS: game.sms created
) else (
    echo [build] ERROR: game.sms not created
    goto error
)

endlocal
exit /b 0

:error
endlocal
exit /b 1
