import sys
import os
import argparse
import subprocess
from pathlib import Path

def run_cmd(cmd, step_name):
    # Prepend tools/wla-dx to PATH for the 'make' step or any tool execution
    script_dir = Path(__file__).parent
    wla_dx_dir = script_dir / "tools" / "wla-dx"
    
    env = os.environ.copy()
    if wla_dx_dir.exists():
        path_sep = ";" if os.name == "nt" else ":"
        env["PATH"] = str(wla_dx_dir) + path_sep + env.get("PATH", "")

    print(f"\n[{step_name}] Running: {' '.join(cmd)}")
    try:
        result = subprocess.run(cmd, capture_output=False, env=env)
        if result.returncode != 0:
            print(f"ERROR: Step '{step_name}' failed with code {result.returncode}", file=sys.stderr)
            sys.exit(result.returncode)
    except FileNotFoundError:
        print(f"WARNING: Command '{cmd[0]}' not found. Skipping '{step_name}'.", file=sys.stderr)
        if cmd[0] == 'make':
            print("To compile the ROM, please install 'make' and 'wla-dx', and run it in the build/ directory.", file=sys.stderr)

def main():
    parser = argparse.ArgumentParser(description="End-to-End NES to SMS Conversion Pipeline")
    parser.add_argument("--nes", required=True, help="Path to the source .nes ROM")
    parser.add_argument("--out", default=None, help="Output directory (defaults to out/<rom_name>_sms)")
    parser.add_argument("--run", action="store_true", help="Run the converted ROM in the emulator")
    args = parser.parse_args()

    nes_path = Path(args.nes)
    if not nes_path.exists():
        print(f"ERROR: Source ROM {nes_path} not found.", file=sys.stderr)
        sys.exit(1)

    if args.out:
        out_dir = Path(args.out)
    else:
        rom_name = nes_path.stem
        out_dir = Path("out") / f"{rom_name}_sms"
        
    work_dir = out_dir / "work"
    assets_dir = out_dir / "assets"
    audio_dir = assets_dir / "audio"
    build_dir = out_dir / "build"
    stubs_dir = build_dir / "stubs"
    
    script_dir = Path(__file__).parent / "skills" / "nes2sms"
    convert_gfx = sys.executable, str(script_dir / "convert_gfx.py")
    sms_packer = sys.executable, str(script_dir / "sms_packer.py")

    manifest_sms = work_dir / "manifest_sms.json"
    symbol_map = work_dir / "symbol_map.json"

    # Step 0: Ingest
    run_cmd([*convert_gfx, "ingest", "--nes", str(nes_path), "--out", str(work_dir)], "Ingest")

    # Step 1: Analyze Mapper
    run_cmd([*convert_gfx, "analyze-mapper", "--manifest", str(manifest_sms), "--out", str(work_dir)], "Analyze Mapper")

    # Step 2: Convert Graphics
    chr_bin = work_dir / "chr.bin"
    prg_bin = work_dir / "prg.bin"
    if not chr_bin.exists():
        # Fallback to creating an empty chr.bin if it uses CHR-RAM without one
        print("Note: chr.bin not found during ingest, creating empty CHR to satisfy convert-gfx.")
        chr_bin.touch()

    run_cmd([*convert_gfx, "convert-gfx", "--chr", str(chr_bin), "--prg", str(prg_bin), "--out", str(assets_dir)], "Convert Graphics")

    # The symbol_map.json is typically generated by convert-gfx if symbols existed, but we may need an empty fallback for stub gen
    if not symbol_map.exists():
        symbol_map.write_text("[]")

    # Step 3: Convert Audio
    run_cmd([*convert_gfx, "convert-audio", "--prg", str(prg_bin), "--out", str(audio_dir)], "Convert Audio")

    # Step 4: Generate Z80 Project Scaffold
    run_cmd([*sms_packer, "generate", "--manifest", str(manifest_sms), "--assets", str(assets_dir), "--out", str(build_dir)], "Generate Scaffold")

    # Step 5: Generate Game Logic Stubs
    run_cmd([*sms_packer, "gen-stubs", "--symbols", str(symbol_map), "--out", str(stubs_dir)], "Generate Stubs")

    # Step 6: Write Makefile
    run_cmd([*sms_packer, "write-makefile", "--out", str(build_dir)], "Write Makefile")

    # Step 7: Build the SMS ROM
    print(f"\n[Build] Running make in {build_dir}")
    run_cmd(["make", "-C", str(build_dir)], "Make")

    sms_rom = build_dir / "game.sms"
    if sms_rom.exists():
        print(f"\nSUCCESS: ROM successfully generated at {sms_rom}")
        if args.run:
            emulator_path = Path(__file__).parent / "emulators" / "blastem" / "blastem.exe"
            if emulator_path.exists():
                print(f"\n[Run] Launching {sms_rom} in BlastEm...")
                subprocess.Popen([str(emulator_path), str(sms_rom)])
            else:
                print(f"\nWARNING: Emulator not found at {emulator_path}. Please run download_emulator.ps1 first.")
    else:
        print("\nWARNING: Make succeeded but game.sms was not found.")

if __name__ == "__main__":
    main()
