"""Z80 stub generator from 6502 symbols."""

from pathlib import Path
from typing import List, Optional

from ...shared.models import Symbol


class StubGenerator:
    """Generates Z80 stub files from 6502 disassembly symbols."""

    def __init__(self, symbols: List[Symbol] = None):
        """
        Initialize stub generator.

        Args:
            symbols: List of symbols from 6502 disassembly
        """
        self.symbols = symbols or []

    def generate_game_logic_stub(self) -> str:
        """Generate game_logic.asm with stubs for each symbol."""
        lines = [
            "; Game Logic Stubs",
            "; Generated by nes2sms",
            "; Port each routine from NES ASM to Z80.",
            "",
            '.section "GameLogic" FREE',
            "",
        ]

        if not self.symbols:
            lines.extend(
                [
                    "; No symbols found - add stubs manually",
                    "GameMain:",
                    ".main_loop:",
                    "    halt",
                    "    jr   .main_loop",
                    "",
                ]
            )
        else:
            for symbol in self.symbols:
                lines.append(self._generate_stub(symbol))

        lines.append(".ends")
        return "\n".join(lines)

    def generate_game_stubs(self) -> str:
        """Generate game_stubs.asm with additional helper stubs."""
        lines = [
            "; Generated stubs — one per NES subroutine",
            "; Replace each stub body with ported Z80 code.",
            "",
            '.section "GameStubs" FREE',
            "",
            ".ends",
        ]
        return "\n".join(lines)

    def _generate_stub(self, symbol: Symbol) -> str:
        """Generate single Z80 stub from 6502 symbol."""
        lines = [
            f"; ============================================================",
            f"; NES STUB: {symbol.name} (NES addr {symbol.address})",
            f"; Type: {symbol.type}",
            f"; Bank: {symbol.bank}",
        ]

        if symbol.comment:
            lines.append(f"; Comment: {symbol.comment}")

        if symbol.disassembly_snippet:
            lines.append(f"; Disassembly: {symbol.disassembly_snippet}")

        lines.extend(
            [
                f"; TODO: Port from 6502 to Z80",
                f"; ============================================================",
                f"{symbol.name}:",
                f"    ; TODO: Implement",
                f"    ret",
                "",
            ]
        )

        return "\n".join(lines)

    def write_stubs(self, output_dir: Path):
        """
        Write stub files to disk.

        Args:
            output_dir: Directory to write stub files
        """
        stubs_dir = output_dir / "stubs"
        stubs_dir.mkdir(parents=True, exist_ok=True)

        game_logic = self.generate_game_logic_stub()
        (stubs_dir / "game_logic.asm").write_text(game_logic, encoding="utf-8")

        game_stubs = self.generate_game_stubs()
        (stubs_dir / "game_stubs.asm").write_text(game_stubs, encoding="utf-8")
