"""WLA-DX assembler templates for Z80/SMS."""

MAIN_ASM = """; SMS Z80 Main Entry
; Generated by nes2sms

.include "memory.inc"

; Include all source files
.include "init.asm"
.include "interrupts.asm"
.include "assets.asm"
.include "hal/vdp.asm"
.include "hal/psg.asm"
.include "hal/input.asm"
.include "hal/mapper.asm"
.include "stubs/game_logic.asm"
.include "stubs/game_stubs.asm"
"""

MEMORY_INC = """.ROMBANKMAP
    BANKSTOTAL NUM_ROM_BANKS
    BANKSIZE $4000
    BANKS NUM_ROM_BANKS
.ENDRO

.MEMORYMAP
    DEFAULTSLOT 0
    SLOT 0 $0000 $4000
    SLOT 1 $4000 $4000
    SLOT 2 $8000 $4000
.ENDME
"""

INIT_ASM = """
.BANK 0 SLOT 0
.ORG $0000

    di
    im 1
    jp   RESET

.ORG $0038
    jp   INT_Handler

.ORG $0066
    jp   NMI_Handler

.ORG $0070
RESET:
    ld   sp, $DFF0
    call VDP_Init
    call PSG_Init
    call ClearVRAM
    ld   a, 2
    ld   ($FFFF), a
    call LoadPalettes
    call LoadTilemap
    call LoadSAT
    ld   a, 3
    ld   ($FFFF), a
    call LoadTiles
    ld   a, 1
    ld   b, %11100000
    call VDP_WriteReg
    ei
    jp   GameMain
"""

INTERRUPTS_ASM = """
.BANK 0 SLOT 0
.ORG $0038
INT_Handler:
    push af
    push bc
    push de
    push hl
    in   a, ($BF)
    pop hl
    pop de
    pop bc
    pop af
    ei
    reti

.ORG $0066
NMI_Handler:
    retn
"""

ASSETS_ASM = """
.BANK 2 SLOT 2
.ORG $0000

PaletteBG:
    .INCBIN "assets/palette_bg.bin"
PaletteSPR:
    .INCBIN "assets/palette_spr.bin"

LoadPalettes:
    ret

LoadTilemap:
    ret

LoadSAT:
    ret

; Tiles are too large for a single bank - would need to split across multiple banks
; For now, using placeholder
LoadTiles:
    ret
"""

HAL_VDP_ASM = """
.BANK 0 SLOT 0
.ORG $0000

.define VDP_DATA_PORT   $BE
.define VDP_CTRL_PORT   $BF

VDP_Init:
    ld   a, 0
    ld   b, %00000000
    call VDP_WriteReg
    ld   a, 1
    ld   b, %00000000
    call VDP_WriteReg
    ld   a, 2
    ld   b, %11000000
    call VDP_WriteReg
    ld   a, 5
    ld   b, %11111110
    call VDP_WriteReg
    ret

VDP_WriteReg:
    ld   c, VDP_CTRL_PORT
    ld   a, %10000000
    or   a
    out  (c), a
    ld   a, b
    out  (c), a
    ret

VDP_SetWriteAddress:
    ld   a, l
    ld   c, VDP_CTRL_PORT
    out  (c), a
    ld   a, h
    or   $40
    out  (c), a
    ret

VDP_WriteData:
    ld   c, VDP_DATA_PORT
    out  (c), a
    ret

ClearVRAM:
    ld   hl, $0000
    call VDP_SetWriteAddress
    ld   bc, $4000
    ld   a, 0
clear_loop:
    ld   c, VDP_DATA_PORT
    out  (c), a
    dec  bc
    ld   a, b
    or   c
    jr   nz, clear_loop
    ret
"""

HAL_PSG_ASM = """
.BANK 0 SLOT 0
.ORG $0000

PSG_Init:
    ld   a, %10011111
    out  ($7F), a
    ld   a, %10111111
    out  ($7F), a
    ld   a, %11011111
    out  ($7F), a
    ld   a, %11111111
    out  ($7F), a
    ret

PSG_SetTone:
    push af
    push bc
    ld   c, $7F
    ld   b, a
    and  $0F
    out  (c), a
    ld   a, h
    and  $03
    rlca
    rlca
    rlca
    rlca
    or   b
    and  $7F
    out  (c), a
    pop bc
    pop af
    ret

PSG_SetVolume:
    ld   c, $7F
    push af
    ld   a, %10000000
    rlca
    rlca
    rlca
    rlca
    and  $7F
    or   b
    and  $9F
    out  (c), a
    pop af
    ret
"""

HAL_INPUT_ASM = """
.BANK 0 SLOT 0
.ORG $0000

.define BTN_UP      %00000001
.define BTN_DOWN    %00000010
.define BTN_LEFT    %00000100
.define BTN_RIGHT   %00001000
.define BTN_1       %00010000
.define BTN_2       %00100000

Input_Init:
    ret

Input_ReadP1:
    in   a, ($DC)
    and  $3F
    cpl
    ret

Input_ReadP2:
    in   a, ($DD)
    and  $3F
    cpl
    ret
"""

HAL_MAPPER_ASM = """
.BANK 0 SLOT 0
.ORG $0000

Mapper_Init:
    xor  a
    ld   ($FFFC), a
    ld   ($FFFD), a
    inc  a
    ld   ($FFFE), a
    inc  a
    ld   ($FFFF), a
    ret

Mapper_SetBank:
    ld   hl, $FFFD
    add  a, l
    ld   l, a
    ld   (hl), b
    ret
"""

GAME_LOGIC_STUB = """
.BANK 0 SLOT 0
.ORG $0000

GameMain:
.main_loop:
    halt
    jr   .main_loop

GameLogicTick:
    ret

UpdateScroll:
    ret

UpdateSAT:
    ret
"""

GAME_STUBS_EMPTY = """
.BANK 0 SLOT 0
.ORG $0000

; Add your stubs here
"""

MAKEFILE_CONTENT = """# WLA-DX Makefile for SMS project
# Generated by nes2sms

ifeq ($(OS),Windows_NT)
    CC = wla-z80.exe
    LD = wlalink.exe
    RM = del /Q
else
    CC = wla-z80
    LD = wlalink
    RM = rm -f
endif

CFLAGS = -v

OBJECTS = main.o init.o interrupts.o assets.o \\
          hal/vdp.o hal/psg.o hal/input.o hal/mapper.o \\
          stubs/game_logic.o

all: game.sms

%.o: %.asm
\t$(CC) $(CFLAGS) $<

game.sms: $(OBJECTS) link.sms
\t$(LD) link.sms $@

clean:
\t$(RM) *.o hal\\*.o stubs\\*.o game.sms 2>nul || $(RM) *.o hal/*.o stubs/*.o game.sms

.PHONY: all clean
"""

LINKER_SCRIPT = """[libraries]

[objects]
main.o
"""
