"""WLA-DX assembler templates for Z80/SMS."""

MAIN_ASM = """
; SMS Z80 Main Entry
; Generated by nes2sms

.include "memory.inc"

; All code is managed in sections here to avoid link errors
.include "init.asm"

.SECTION "Interrupts" BANK 0 SLOT 0 FREE
.include "interrupts.asm"
.ENDS

.SECTION "HAL" BANK 0 SLOT 0 FREE
.include "hal/vdp.asm"
.include "hal/psg.asm"
.include "hal/input.asm"
.include "hal/mapper.asm"
.include "hal/support.asm"
.ENDS

.SECTION "Assets_Tiles" BANK 1 SLOT 1 FREE
; Tiles takes 16KB, putting in its own bank
Tiles:
    .INCBIN "assets/tiles.bin"
Tiles_End:
.ENDS

.SECTION "Assets_Small" BANK 0 SLOT 0 FREE
PaletteBG:
    .INCBIN "assets/palette_bg.bin"
PaletteSPR:
    .INCBIN "assets/palette_spr.bin"

.include "assets.asm" ; Only contains loading logic now
.ENDS

.SECTION "GameCode" BANK 2 SLOT 2 FREE
.include "stubs/game_logic.asm"
.include "stubs/game_stubs.asm"
.ENDS
"""

MEMORY_INC = """.ROMBANKMAP
    BANKSTOTAL 8
    BANKSIZE $4000
    BANKS 8
.ENDRO

.MEMORYMAP
    DEFAULTSLOT 0
    SLOT 0 $0000 $4000
    SLOT 1 $4000 $4000
    SLOT 2 $8000 $4000
    SLOT 3 $C000 $2000
.ENDME
"""

INIT_ASM = """
.SECTION "Vector0000" FORCE ORG $0000
    di
    im 1
    jp   RESET
.ENDS

.SECTION "Vector0038" FORCE ORG $0038
    jp   INT_Handler
.ENDS

.SECTION "Vector0066" FORCE ORG $0066
    jp   SMS_NMI_Handler
.ENDS

.SECTION "ResetCode" FORCE ORG $0070
RESET:
    ld   sp, $DFF0
    call VDP_Init
    call PSG_Init
    call Mapper_Init
    call ClearVRAM
    call LoadPalettes
    call LoadTiles
    call LoadTilemap
    call LoadSAT
    ld   a, 1
    ld   b, %11100000
    call VDP_WriteReg
    ei
    jp   GameMain
.ENDS
"""

INTERRUPTS_ASM = """
INT_Handler:
    push af
    push bc
    push de
    push hl
    in   a, ($BF)
    call NMI_Handler
    pop hl
    pop de
    pop bc
    pop af
    ei
    reti

SMS_NMI_Handler:
    retn
"""

ASSETS_ASM = """

.export LoadPalettes
LoadPalettes:
    ; Load BG palette
    ld   hl, $C000
    call VDP_SetWriteAddress
    ld   hl, PaletteBG
    ld   bc, 16
    call VDP_CopyBytes
    
    ; Load Sprite palette
    ld   hl, $C010
    call VDP_SetWriteAddress
    ld   hl, PaletteSPR
    ld   bc, 16
    call VDP_CopyBytes
    ret

.export LoadTiles
LoadTiles:
    ld   hl, $0000
    call VDP_SetWriteAddress
    ld   hl, Tiles
    ld   bc, Tiles_End - Tiles
    call VDP_CopyBytes
    ret

.export LoadTilemap
LoadTilemap:
    ; Clear name table and apply coarse priority zoning.
    ld   hl, $3800
    call VDP_SetWriteAddress
    ld   d, 0
.row_loop:
    ld   e, 32
    ld   a, d
    cp   PRIORITY_SPLIT_TILE
    jr   c, .row_no_prio
    ld   c, $10
    jr   .row_prio_ready
.row_no_prio:
    ld   c, $00
.row_prio_ready:
.col_loop:
    xor  a
    out  ($BE), a
    ld   a, c
    out  ($BE), a
    dec  e
    jr   nz, .col_loop
    inc  d
    ld   a, d
    cp   28
    jr   nz, .row_loop
    ret

.export LoadSAT
LoadSAT:
    ; Hide all sprites by placing end marker in first SAT Y entry.
    ld   hl, $3F00
    call VDP_SetWriteAddress
    ld   a, $D0
    out  ($BE), a
    ret

.export SpriteVariantMap
SpriteVariantMap:
    .INCBIN "assets/sprite_variant_map.bin"

; Helper to copy BC bytes from HL to VDP
VDP_CopyBytes:
    ld   a, (hl)
    out  ($BE), a
    inc  hl
    dec  bc
    ld   a, b
    or   c
    jr   nz, VDP_CopyBytes
    ret
"""

HAL_VDP_ASM = """
.export VDP_Init
.export VDP_WriteReg
.export VDP_SetWriteAddress
.export VDP_WriteData
.export ClearVRAM

.define VDP_DATA_PORT   $BE
.define VDP_CTRL_PORT   $BF

VDP_Init:
    ; Register 0: Mode 4, Enable line interrupts
    ld   a, 0
    ld   b, %00000110
    call VDP_WriteReg
    ; Register 1: Mode 4, 192 lines, keep display disabled during asset upload
    ld   a, 1
    ld   b, %00100000
    call VDP_WriteReg
    ; Register 2: Name Table Base Address ($3800)
    ld   a, 2
    ld   b, %11101110
    call VDP_WriteReg
    ; Register 5: Sprite Attribute Table Base ($3F00)
    ld   a, 5
    ld   b, $7E
    call VDP_WriteReg
    ; Register 6: Sprite tile base (first 256 tiles)
    ld   a, 6
    ld   b, $00
    call VDP_WriteReg
    ret

VDP_WriteReg:
    ; A = Register index
    ; B = Data value
    push af
    ld   a, b
    out  (VDP_CTRL_PORT), a ; First byte: Data
    pop  af
    or   %10000000          ; Second byte: Register Index | $80
    out  (VDP_CTRL_PORT), a
    ret

VDP_SetWriteAddress:
    ld   a, l
    ld   c, VDP_CTRL_PORT
    out  (c), a
    ld   a, h
    or   $40
    out  (c), a
    ret

VDP_WriteData:
    ld   c, VDP_DATA_PORT
    out  (c), a
    ret

ClearVRAM:
    ld   hl, $0000
    call VDP_SetWriteAddress
    ld   bc, $4000
    xor  a
.clear_loop:
    out  ($BE), a
    dec  bc
    ld   a, b
    or   c
    jr   nz, .clear_loop
    ret
"""

HAL_PSG_ASM = """
.export PSG_Init
.export PSG_SetTone
.export PSG_SetVolume

PSG_Init:
    ld   a, %10011111
    out  ($7F), a
    ld   a, %10111111
    out  ($7F), a
    ld   a, %11011111
    out  ($7F), a
    ld   a, %11111111
    out  ($7F), a
    ret

PSG_SetTone:
    push af
    push bc
    ld   c, $7F
    ld   b, a
    and  $0F
    out  (c), a
    ld   a, h
    and  $03
    rlca
    rlca
    rlca
    rlca
    or   b
    and  $7F
    out  (c), a
    pop bc
    pop af
    ret

PSG_SetVolume:
    ld   c, $7F
    push af
    ld   a, %10000000
    rlca
    rlca
    rlca
    rlca
    and  $7F
    or   b
    and  $9F
    out  (c), a
    pop af
    ret
"""

HAL_INPUT_ASM = """
.export Input_Init
.export Input_ReadP1
.export Input_ReadP2

.define BTN_UP      %00000001
.define BTN_DOWN    %00000010
.define BTN_LEFT    %00000100
.define BTN_RIGHT   %00001000
.define BTN_1       %00010000
.define BTN_2       %00100000

Input_Init:
    ret

Input_ReadP1:
    in   a, ($DC)
    and  $3F
    cpl
    ret

Input_ReadP2:
    in   a, ($DD)
    and  $3F
    cpl
    ret
"""

HAL_MAPPER_ASM = """
.export Mapper_Init
.export Mapper_SetBank

Mapper_Init:
    xor  a
    ld   ($FFFC), a
    ld   ($FFFD), a
    inc  a
    ld   ($FFFE), a
    inc  a
    ld   ($FFFF), a
    ret

Mapper_SetBank:
    ld   hl, $FFFD
    add  a, l
    ld   l, a
    ld   (hl), b
    ret
"""

GAME_LOGIC_STUB = """

GameMain:
.main_loop:
    halt
    jr   .main_loop

GameLogicTick:
    ret

UpdateScroll:
    ret

UpdateSAT:
    ret
"""

GAME_STUBS_EMPTY = """

; Add your stubs here

.ifndef NMI_Handler
NMI_Handler:
    ret
.endif
"""

MAKEFILE_CONTENT = """# WLA-DX Makefile for SMS project
# Generated by nes2sms

ifeq ($(OS),Windows_NT)
    CC = wla-z80.exe
    LD = wlalink.exe
    RM = del /Q
else
    CC = wla-z80
    LD = wlalink
    RM = rm -f
endif

CFLAGS = -v

OBJECTS = main.o

all: game.sms

%.o: %.asm
\t$(CC) $(CFLAGS) $<

game.sms: $(OBJECTS) link.sms
\t$(LD) link.sms $@

clean:
\t$(RM) *.o game.sms 2>nul || $(RM) *.o game.sms

.PHONY: all clean
"""

LINKER_SCRIPT = """[libraries]

[objects]
main.o
"""
