"""Info file generator for da65."""

from dataclasses import dataclass
from typing import List, Optional, Dict
from pathlib import Path


@dataclass
class CodeRange:
    """Represents a code or data range for da65."""

    start: int
    end: int
    range_type: str  # CODE, BYTETABLE, WORDTABLE, TEXTTABLE, SKIP
    name: Optional[str] = None
    comment: Optional[str] = None

    def to_info_line(self) -> str:
        """Convert to da65 info file RANGE directive."""
        lines = [f"RANGE {{ START ${self.start:04X}; END ${self.end:04X}; TYPE {self.range_type};"]
        if self.name:
            lines.append(f'    NAME "{self.name}";')
        if self.comment:
            lines.append(f'    COMMENT "{self.comment}";')
        lines.append("};")
        return "\n".join(lines)


@dataclass
class Label:
    """Represents a label for da65."""

    name: str
    address: int
    comment: Optional[str] = None
    size: Optional[int] = None

    def to_info_line(self) -> str:
        """Convert to da65 info file LABEL directive."""
        lines = [f'LABEL {{ NAME "{self.name}"; ADDR ${self.address:04X};']
        if self.comment:
            lines.append(f'    COMMENT "{self.comment}";')
        if self.size:
            lines.append(f"    SIZE {self.size};")
        lines.append("};")
        return "\n".join(lines)


@dataclass
class InfoFileOptions:
    """Global options for da65 info file."""

    input_name: Optional[str] = None
    output_name: Optional[str] = None
    start_addr: int = 0x8000
    cpu: str = "6502"
    page_length: int = 0  # 0 = no paging
    comment_level: int = 2
    hex_offsets: bool = True
    mnemonic_column: int = 15
    argument_column: int = 20
    comment_column: int = 40

    def to_info_section(self) -> str:
        """Convert to da65 info file GLOBAL section."""
        lines = ["GLOBAL {"]
        lines.append(f"    STARTADDR ${self.start_addr:04X};")
        lines.append(f'    CPU "{self.cpu}";')
        lines.append(f"    PAGELENGTH {self.page_length};")
        lines.append(f"    COMMENTS {self.comment_level};")
        lines.append(f"    HEXOFFS {'TRUE' if self.hex_offsets else 'FALSE'};")
        lines.append(f"    MNEMONICCOLUMN {self.mnemonic_column};")
        lines.append(f"    ARGUMENTCOLUMN {self.argument_column};")
        lines.append(f"    COMMENTCOLUMN {self.comment_column};")
        if self.input_name:
            lines.append(f'    INPUTNAME "{self.input_name}";')
        if self.output_name:
            lines.append(f'    OUTPUTNAME "{self.output_name}";')
        lines.append("};")
        return "\n".join(lines)


class InfoFileGenerator:
    """
    Generates da65 info files.

    SRP: Only generates info file content.
    ISP: Small focused methods for each directive type.
    """

    def __init__(self, options: Optional[InfoFileOptions] = None):
        """
        Initialize generator.

        Args:
            options: Global options for info file
        """
        self.options = options or InfoFileOptions()

    def generate(
        self,
        code_ranges: List[CodeRange],
        labels: List[Label],
        segments: Optional[List[Dict]] = None,
    ) -> str:
        """
        Generate complete info file content.

        Args:
            code_ranges: Code and data ranges
            labels: Labels to define
            segments: Optional segment definitions

        Returns:
            Complete info file as string
        """
        lines = [
            "; da65 Info File",
            "; Generated by nes2sms",
            "",
            self.options.to_info_section(),
            "",
        ]

        # Add ranges
        if code_ranges:
            lines.append("; Code and Data Ranges")
            for range in code_ranges:
                lines.append(range.to_info_line())
            lines.append("")

        # Add labels
        if labels:
            lines.append("; Labels")
            for label in labels:
                lines.append(label.to_info_line())
            lines.append("")

        # Add segments if provided
        if segments:
            lines.append("; Segments")
            for seg in segments:
                lines.append(self._segment_to_info(seg))
            lines.append("")

        return "\n".join(lines)

    def _segment_to_info(self, segment: Dict) -> str:
        """Convert segment dict to info line."""
        return (
            f"SEGMENT {{ START ${segment.get('start', 0):04X}; "
            f"END ${segment.get('end', 0xFFFF):04X}; "
            f'NAME "{segment.get("name", "CODE")}"; }};'
        )

    def from_symbols(
        self,
        symbols: List[Dict],
        code_ranges: List[tuple],
        data_ranges: List[tuple],
    ) -> str:
        """
        Generate info file from symbol extractor data.

        Args:
            symbols: List of symbol dicts with name, address
            code_ranges: List of (start, end) tuples for code
            data_ranges: List of (start, end) tuples for data

        Returns:
            Complete info file as string
        """
        # Convert symbols to labels
        labels = [
            Label(
                name=sym["name"],
                address=sym["address"]
                if isinstance(sym["address"], int)
                else int(sym["address"].replace("$", ""), 16),
                comment=sym.get("comment"),
            )
            for sym in symbols
        ]

        # Convert ranges
        code_range_objs = [CodeRange(start=s, end=e, range_type="CODE") for s, e in code_ranges]
        data_range_objs = [
            CodeRange(start=s, end=e, range_type="BYTETABLE") for s, e in data_ranges
        ]

        return self.generate(
            code_ranges=code_range_objs + data_range_objs,
            labels=labels,
        )

    def write(
        self,
        output_path: Path,
        code_ranges: List[CodeRange],
        labels: List[Label],
    ):
        """
        Write info file to disk.

        Args:
            output_path: Path to write info file
            code_ranges: Code and data ranges
            labels: Labels to define
        """
        content = self.generate(code_ranges, labels)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(content, encoding="utf-8")
