#!/usr/bin/env python3
"""
nes2sms/scripts/sms_packer.py
Generates SMS Z80 project scaffold (WLA-DX or SDCC), patches SMS header/checksum,
writes Makefile, and runs emulator smoke tests.

Usage:
  python3 sms_packer.py generate   --manifest manifest_sms.json --assets assets/ \
                                    [--backend wla-dx|sdcc] [--mapper sega] --out build/
  python3 sms_packer.py gen-stubs  --symbols symbol_map.json --out build/stubs/
  python3 sms_packer.py patch-header  --rom game.sms [--region 6] --out game_patched.sms
  python3 sms_packer.py write-makefile --out build/
  python3 sms_packer.py test       --rom game.sms [--emulator emulicious] --report report.txt
"""

import sys
import os
import json
import struct
import hashlib
import subprocess
import argparse
from pathlib import Path

# ---------------------------------------------------------------------------
# SMS Header Constants
# ---------------------------------------------------------------------------

SMS_HEADER_MAGIC = b'TMR SEGA'
SMS_HEADER_OFFSET_32K = 0x7FF0

REGION_CODES = {
    'japan':    4,
    'export':   5,   # GG overseas
    'sms-us':   6,
    'sms-eu':   7,
    'sms-jp':   5,
    'gg-jp':    6,
}

ROM_SIZE_CODES = {
    8192:    0xA,
    16384:   0xB,
    32768:   0xC,
    49152:   0xD,
    65536:   0xE,
    131072:  0xF,
}


def compute_checksum(data: bytes, header_offset: int = SMS_HEADER_OFFSET_32K) -> int:
    total = 0
    for i, b in enumerate(data):
        if header_offset <= i <= header_offset + 15:
            continue
        total += b
    return total & 0xFFFF


def patch_sms_header(data: bytearray, region: int = 6) -> bytearray:
    size_code = 0xC  # default 32KB
    for size, code in ROM_SIZE_CODES.items():
        if len(data) >= size:
            size_code = code

    offset = SMS_HEADER_OFFSET_32K
    if len(data) < offset + 16:
        data.extend(b'\x00' * (offset + 16 - len(data)))

    # Write magic
    data[offset:offset + 8] = SMS_HEADER_MAGIC
    data[offset + 8] = 0x00
    data[offset + 9] = 0x00

    # Compute and write checksum
    checksum = compute_checksum(bytes(data), offset)
    struct.pack_into('<H', data, offset + 10, checksum)

    # Product code (homebrew: all zeros)
    data[offset + 12] = 0x00
    data[offset + 13] = 0x00
    data[offset + 14] = 0x00

    # Region + size
    data[offset + 15] = ((region & 0xF) << 4) | (size_code & 0xF)
    return data


# ---------------------------------------------------------------------------
# WLA-DX Linker Script Generator
# ---------------------------------------------------------------------------

def write_linker_script(out_dir: Path, rom_banks: int = 4):
    content = f"""; WLA-DX Linker Script for SMS
; Generated by nes2sms/scripts/sms_packer.py

[OBJECTS]
main.o
"""
    (out_dir / 'link.sms').write_text(content, encoding='utf-8')


# ---------------------------------------------------------------------------
# Z80 Source File Generators
# ---------------------------------------------------------------------------

MAIN_ASM = """; SMS Z80 Main Entry
; Generated by nes2sms/scripts/sms_packer.py

.include "memory.inc"
.include "init.asm"
.include "interrupts.asm"
.include "assets.asm"
.include "hal/vdp.asm"
.include "hal/psg.asm"
.include "hal/input.asm"
.include "hal/mapper.asm"
.include "stubs/game_logic.asm"
.include "stubs/game_stubs.asm"
"""

MEMORY_INC = """.MEMORYMAP
    DEFAULTSLOT 0
    SLOT 0 $0000 $4000
    SLOT 1 $4000 $4000
    SLOT 2 $8000 $4000
.ENDME

.ROMBANKMAP
    BANKSTOTAL {banks}
    BANKSIZE $4000
    BANKS {banks}
.ENDRO
"""

ASSETS_ASM = """; SMS Asset Data & Loaders
; Generated by nes2sms/scripts/sms_packer.py

; ============================================================
; Bank 2: Palettes and Tilemap
; ============================================================
.section "Bank2Data" BANK 2 SLOT 2

PaletteBG:
    .incbin "assets/palette_bg.bin"
PaletteSPR:
    .incbin "assets/palette_spr.bin"

LoadPalettes:
    ; Write BG palette (16 entries → CRAM $0000–$000F)
    ld   a, $00
    out  ($BF), a
    ld   a, $C0
    out  ($BF), a
    ld   hl, PaletteBG
    ld   b, 16
.bg_pal_loop:
    ld   a, (hl)
    out  ($BE), a
    inc  hl
    djnz .bg_pal_loop

    ; Write SPR palette (16 entries → CRAM $0010–$001F)
    ld   a, $10
    out  ($BF), a
    ld   a, $C0
    out  ($BF), a
    ld   hl, PaletteSPR
    ld   b, 16
.spr_pal_loop:
    ld   a, (hl)
    out  ($BE), a
    inc  hl
    djnz .spr_pal_loop
    ret

LoadTilemap:
    ld   a, $00
    out  ($BF), a
    ld   a, $40 | ($38)
    out  ($BF), a
    ld   hl, TilemapData
    ld   bc, TilemapData_END - TilemapData
.tmap_loop:
    ld   a, (hl)
    out  ($BE), a
    inc  hl
    dec  bc
    ld   a, b
    or   c
    jr   nz, .tmap_loop
    ret

TilemapData:
    .incbin "assets/tilemap.bin"
TilemapData_END:

.ends

; ============================================================
; Bank 3: Tiles
; ============================================================
.section "Bank3Data" BANK 3 SLOT 2
LoadTiles:
    ld   a, $00
    out  ($BF), a
    ld   a, $40
    out  ($BF), a
    ld   hl, TilesData
    ld   bc, TilesData_END - TilesData
.tile_loop:
    ld   a, (hl)
    out  ($BE), a
    inc  hl
    dec  bc
    ld   a, b
    or   c
    jr   nz, .tile_loop
    ret

TilesData:
    .incbin "assets/tiles.bin"
TilesData_END:

LoadSAT:
    ld   a, $00
    out  ($BF), a
    ld   a, $40 | $3F
    out  ($BF), a
    ld   a, $D0
    ld   b, 64
.sat_loop:
    out  ($BE), a
    djnz .sat_loop
    ret

.ends
"""

INIT_ASM = """; SMS Z80 Initialization
; Generated by nes2sms/scripts/sms_packer.py
; Reference: SKILL.md § Step 4 — Generate Z80 Project Scaffold

.bank 0 slot 0
; .org $0000 is redundant with slot 0

; ============================================================
; RESET VECTOR — entry point after power on
; ============================================================
RESET:
    di                          ; disable interrupts
    im 1                        ; interrupt mode 1: INT → $0038
    ld   sp, $DFF0              ; stack top (SMS RAM safe zone)

    ; Initialize hardware
    call VDP_Init               ; configure VDP registers
    call PSG_Init               ; silence all PSG channels
    call ClearVRAM              ; zero 16 KB VRAM

    ; Map asset banks
    ld   a, 2                   ; Bank 2: Palettes + Tilemap
    ld   ($FFFF), a             ; Map to Slot 2 ($8000)
    
    call LoadPalettes
    call LoadTilemap
    call LoadSAT

    ld   a, 3                   ; Bank 3: Tiles
    ld   ($FFFF), a             ; Map to Slot 2 ($8000)
    call LoadTiles

    ; Enable display and interrupts
    ld   a, %01100100           ; VDP Reg1: display enable + VBlank IRQ
    ld   b, 1
    call VDP_SetRegister
    ei

    ; Jump to ported game entry point
    jp   GameMain

"""

INTERRUPTS_ASM = """; SMS Z80 Interrupt Handlers
; Generated by nes2sms/scripts/sms_packer.py
; Reference: SKILL.md § Step 4, references/hardware_diff.md § Interrupt Architecture

.bank 0 slot 0

; ============================================================
; INT Handler at $0038 — Z80 IM 1 (VBlank / line counter)
; CRITICAL: Must read $BF (VDP status) to clear interrupt flag.
; ============================================================
.org $0038
INT_Handler:
    push af
    push bc
    push de
    push hl
    push ix
    push iy

    in   a, ($BF)               ; READ VDP STATUS — MANDATORY (clears INT)

    ; ---- Ported NES NMI body goes here ----
    ; call UpdateSAT            ; replaces NES OAM DMA ($4014)
    ; call UpdateScroll         ; replaces NES PPU scroll ($2005×2)
    ; call GameLogicTick        ; ported NMI game-update routine

    ; TODO: Uncomment and implement the above calls in stubs/game_logic.asm

    pop iy
    pop ix
    pop hl
    pop de
    pop bc
    pop af
    ei
    reti


; ============================================================
; NMI Handler at $0066 — PAUSE button (non-maskable)
; ============================================================
.org $0066
NMI_Handler:
    ; TODO: Implement PAUSE menu or toggle pause state
    ; This fires when the user presses the PAUSE button on the SMS.
    ; If the NES game had a Start button pause handler, port it here.
    retn

"""

HAL_VDP_ASM = """; SMS VDP Hardware Abstraction Layer
; Generated by nes2sms/scripts/sms_packer.py
; Reference: references/hardware_diff.md § VDP Register Map
;
; NES PPU → SMS VDP mapping:
;   $2000 (PPUCTRL)        → VDP_SetRegister (Reg 0/1)
;   $2001 (PPUMASK)        → VDP_SetRegister (Reg 0)
;   $2005×2 (PPUSCROLL)    → VDP_SetScrollX + VDP_SetScrollY
;   $2006/$2007 (VRAM addr)→ VDP_SetWriteAddress + out ($BE)
;   $4014 (OAM DMA)        → UpdateSAT
;   read $2002 (PPUSTATUS) → in a, ($BF)

.section "VDP_HAL" FREE
; VDP_SetRegister: A = register number (0–10), B = value
VDP_SetRegister:
    ld   c, $BF
    out  (c), b                 ; data byte
    ld   a, %10000000
    or   c                      ; set register write flag
    ; NOTE: C already = $BF, so A = $BF | $80 — correct for reg <= 15
    ; Actually: A = $80 | reg_num. Caller must ensure A = reg before call.
    ; Recommended: inline helper below.
    ret

; VDP_WriteReg: write value V to VDP register N
; Call pattern: ld a, N; ld b, V; call VDP_WriteReg
VDP_WriteReg:
    push af
    ld   c, $BF
    out  (c), b                 ; value byte
    pop  af
    or   $80                    ; register command bit
    out  (c), a                 ; register select
    ret

; VDP_Init: initialize VDP with standard Mode 4 settings
VDP_Init:
    ld   b, VDP_INIT_TABLE_END - VDP_INIT_TABLE
    ld   hl, VDP_INIT_TABLE
    ld   e, 0                   ; register index
.vdp_init_loop:
    ld   a, (hl)
    ld   c, $BF
    out  (c), a                 ; data byte
    ld   a, $80
    or   e
    out  (c), a                 ; register number
    inc  hl
    inc  e
    djnz .vdp_init_loop
    ret

VDP_INIT_TABLE:
    .db %00000100               ; Reg 0: Mode 4, no left column blank, line IRQ off
    .db %01100100               ; Reg 1: display on, VBlank IRQ on, 8x8 sprites
    .db %11111111 & (($3800 >> 10) << 1 | 1)  ; Reg 2: name table at $3800
    .db $FF                     ; Reg 3: (ignored in Mode 4)
    .db $FF                     ; Reg 4: (ignored in Mode 4)
    .db %11111111 & (($3F00 >> 7) << 1 | 1)   ; Reg 5: SAT at $3F00
    .db %11111011               ; Reg 6: sprite tiles from $0000
    .db $00                     ; Reg 7: border color index 0
    .db $00                     ; Reg 8: X scroll = 0
    .db $00                     ; Reg 9: Y scroll = 0
    .db $FF                     ; Reg 10: line counter (disabled)
VDP_INIT_TABLE_END:

; VDP_SetWriteAddress: HL = VRAM address for write
VDP_SetWriteAddress:
    ld   a, l
    out  ($BF), a
    ld   a, h
    or   $40                    ; write address command (bits 7:6 = 01)
    out  ($BF), a
    ret

; VDP_SetScrollX: A = horizontal scroll value
; NOTE: SMS scrolls opposite direction to NES. Invert if needed:
;   SMS_X = 256 - NES_X
VDP_SetScrollX:
    ld   b, a
    ld   a, 8                   ; VDP register 8
    call VDP_WriteReg
    ret

; VDP_SetScrollY: A = vertical scroll value
VDP_SetScrollY:
    ld   b, a
    ld   a, 9                   ; VDP register 9
    call VDP_WriteReg
    ret

; ClearVRAM: zero all 16KB of VRAM
ClearVRAM:
    ld   a, $00
    out  ($BF), a
    ld   a, $40
    out  ($BF), a
    ld   hl, $4000
.clear_loop:
    xor  a
    out  ($BE), a
    dec  hl
    ld   a, h
    or   l
    jr   nz, .clear_loop
    ret

.ends
"""

HAL_PSG_ASM = r"""; SMS PSG (SN76489) Hardware Abstraction Layer
; Generated by nes2sms/scripts/sms_packer.py
; Reference: references/hardware_diff.md § Audio Conversion

.section "PSG_HAL" FREE

PSG_PORT .equ $7F

; PSG_Init: silence all channels
PSG_Init:
    ld   a, %10011111           ; Tone1: attenuation = 15 (silent)
    out  (PSG_PORT), a
    ld   a, %10111111           ; Tone2: attenuation = 15
    out  (PSG_PORT), a
    ld   a, %11011111           ; Tone3: attenuation = 15
    out  (PSG_PORT), a
    ld   a, %11111111           ; Noise: attenuation = 15
    out  (PSG_PORT), a
    ret

; PSG_SetTone: DE = channel latch (0=T1,1=T2,2=T3), HL = period (10-bit)
; Frequency formula: period = 3579545 / (32 * Hz)
PSG_SetTone:
    ; First byte: latch + low 4 bits of period
    ld   a, h
    and  $03                    ; high 2 bits of period (max 10-bit)
    ; Build latch byte: %1cc00000 | (D<<5) | (period & 0xF)
    ld   a, l
    and  $0F
    ld   b, a
    ld   a, d
    rlca \ rlca \ rlca \ rlca \ rlca  ; shift channel to bits 6:5
    or   %10000000              ; set latch bit
    or   b
    out  (PSG_PORT), a
    ; Second byte: high 6 bits of period
    ld   a, l
    rlca \ rlca \ rlca \ rlca   ; shift right 4 (= low 4 used above)
    or   h                      ; OR in high bits
    and  $3F                    ; mask to 6 bits
    out  (PSG_PORT), a
    ret

; PSG_SetVolume: D = channel (0–3), E = attenuation (0=loud, 15=silent)
PSG_SetVolume:
    ld   a, d
    rlca \ rlca \ rlca \ rlca \ rlca  ; shift channel to bits 6:5
    or   %10010000              ; set latch + volume flag (bit 4=1)
    ld   b, a
    ld   a, e
    and  $0F
    or   b
    out  (PSG_PORT), a
    ret

.ends
"""

HAL_INPUT_ASM = """; SMS Input HAL
; Generated by nes2sms/scripts/sms_packer.py
; Reference: references/hardware_diff.md § Input / Control Mapping
;
; NES controller → SMS joypad mapping (default):
;   A      → Button 1 (bit 4 of $DC, active low)
;   B      → Button 2 (bit 5 of $DC, active low)
;   Start  → PAUSE (NMI at $0066)
;   Select → Button1 + Button2 (held together)
;   D-Pad  → D-Pad (1:1)
;
; Button bits in port $DC (Joypad 1):
;   bit 0 = Up    bit 1 = Down   bit 2 = Left  bit 3 = Right
;   bit 4 = Btn1  bit 5 = Btn2
;   (0 = pressed, 1 = released — active LOW)

.section "Input_HAL" FREE

; Input_ReadJoypad1: reads joypad 1 into A
; Returns: A = button state (bit = 0 means pressed)
; Use Input_IsPressed macro to test individual buttons.
Input_ReadJoypad1:
    in   a, ($DC)
    cpl                         ; invert: now 1=pressed, 0=released
    and  $3F                    ; mask to 6 bits (Up/Down/Left/Right/Btn1/Btn2)
    ret

; Bit constants for joypad (after CPL — 1=pressed)
.define INPUT_UP    %00000001
.define INPUT_DOWN  %00000010
.define INPUT_LEFT  %00000100
.define INPUT_RIGHT %00001000
.define INPUT_BTN1  %00010000      ; NES: A button
.define INPUT_BTN2  %00100000      ; NES: B button

; Edge detection helpers (store previous state in RAM)
; Usage:
;   call Input_ReadJoypad1      ; A = current state
;   ld   (Input_CurrState), a
;   ld   b, a
;   ld   a, (Input_PrevState)
;   cpl
;   and  b                      ; A = newly pressed buttons
;   ld   (Input_PrevState), b

.ends
"""

HAL_MAPPER_ASM = """; SMS Sega Mapper HAL
; Generated by nes2sms/scripts/sms_packer.py
; Reference: references/hardware_diff.md § Mapper Mapping Table
;
; Sega Mapper registers (in RAM at $FFFC–$FFFF):
;   $FFFC: control (bit 3=RAM at slot2, bit 2=RAM at slot0, bit 0=RAM enable)
;   $FFFD: slot 0 bank select (page 0 = $0000–$3FFF)
;   $FFFE: slot 1 bank select (page 1 = $4000–$7FFF)
;   $FFFF: slot 2 bank select (page 2 = $8000–$BFFF)
;
; Bank 0 is ALWAYS present at $0000 (contains INT/NMI vectors).
; Bank N is selected by writing N to the corresponding slot register.

.section "Mapper_HAL" FREE

; Mapper_Init: set default banks (0/1/2)
Mapper_Init:
    ld   a, 0
    ld   ($FFFD), a             ; slot 0 = bank 0
    ld   a, 1
    ld   ($FFFE), a             ; slot 1 = bank 1
    ld   a, 2
    ld   ($FFFF), a             ; slot 2 = bank 2
    ret

; Mapper_SetSlot1: A = bank number to map into slot 1 ($4000–$7FFF)
; This replaces NES mapper bank-switch writes (e.g. STA $8000 for UxROM)
Mapper_SetSlot1:
    ld   ($FFFE), a
    ret

; Mapper_SetSlot2: A = bank number to map into slot 2 ($8000–$BFFF)
Mapper_SetSlot2:
    ld   ($FFFF), a
    ret

.ends
"""

GAME_LOGIC_STUB_ASM = """; Game Logic Stubs
; Generated by nes2sms/scripts/sms_packer.py
; All NES subroutines are stubbed here.
; Port each routine from NES ASM (see nes-disasm output) to Z80.
; Reference: SKILL.md § Step 5 — Generate Game Logic Stubs

.section "GameLogic" FREE

; ============================================================
; GameMain — entry point (replaces NES RESET routine body)
; TODO: port NES RESET handler body here
; ============================================================
GameMain:
.main_loop:
    halt                        ; wait for INT (VBlank)
    jr   .main_loop             ; loop forever; real logic in INT_Handler


; ============================================================
; NES NMI equivalent — called from INT_Handler
; TODO: port NES NMI body here (OAM DMA, scroll, game tick)
; ============================================================
GameLogicTick:
    ; call UpdateSAT
    ; call UpdateScroll
    ; call RunGameFrame
    ret


; ============================================================
; Scroll update stub
; TODO: read scroll_x and scroll_y from RAM; call HAL
; ============================================================
UpdateScroll:
    ; ld   a, (scroll_x_sms)
    ; call VDP_SetScrollX
    ; ld   a, (scroll_y_sms)
    ; call VDP_SetScrollY
    ret


; ============================================================
; SAT update stub
; TODO: build SAT from sprite table in RAM, upload to VRAM $3F00
; ============================================================
UpdateSAT:
    ; ld   hl, SpriteTable       ; RAM sprite data
    ; ld   de, $3F00             ; VRAM SAT address
    ; ... (set VRAM write addr, stream Y table, then X+tile table)
    ret


; ============================================================
; TODO STUBS — add one block per NES subroutine from symbols.json
; ============================================================
; Example pattern:
;
; ; NES addr: $8042 | Bank: 00 | Label: Bank00_UpdateScroll
; ; NES ASM:  LDA scroll_x / STA $2005 / LDA scroll_y / STA $2005
; Bank00_UpdateScroll:
;     ld   a, (scroll_x)
;     call VDP_SetScrollX
;     ld   a, (scroll_y)
;     call VDP_SetScrollY
;     ret

.ends
"""

MAKEFILE_CONTENT = """# Makefile for NES → SMS port project (WLA-DX backend)
# Generated by nes2sms/scripts/sms_packer.py

WLA = wla-z80
LINK = wlalink

OBJECTS = main.o
ROM = game.sms

all: $(ROM)

$(ROM): $(OBJECTS) link.sms
\t$(LINK) -v link.sms $(ROM)

%.o: %.asm
\t$(WLA) -o $@ $<

hal/%.o: hal/%.asm
\t$(WLA) -o $@ $<

stubs/%.o: stubs/%.asm
\t$(WLA) -o $@ $<

clean:
\trm -f $(OBJECTS) $(ROM)

.PHONY: all clean
"""

# ---------------------------------------------------------------------------
# Stub Generator from symbols.json
# ---------------------------------------------------------------------------

def gen_stubs_from_symbols(symbols: list, out_dir: Path):
    lines = [
        '; Generated stubs — one per NES subroutine in symbols.json',
        '; Replace each stub body with ported Z80 code.',
        '; Reference: SKILL.md § Step 5',
        '',
        '.section "GameStubs" FREE',
        '',
    ]
    for sym in symbols:
        name = sym.get('name', 'Unknown')
        addr = sym.get('cpu_addr', '?')
        bank = sym.get('bank', '?')
        comment = sym.get('comment', '')
        lines += [
            f'; {"="*60}',
            f'; NES Label: {name}',
            f'; NES CPU addr: {addr} | Bank: {bank}',
            f'; {comment}' if comment else '; (no comment in symbols.json)',
            f'; TODO: port this routine to Z80',
            f'; {"="*60}',
            f'NES_{name}:',
            f'    ; TODO',
            f'    ret',
            '',
        ]
    lines.append('.ends')
    (out_dir / 'game_stubs.asm').write_text('\n'.join(lines), encoding='utf-8')
    print(f"[gen-stubs] Wrote {len(symbols)} stubs to {out_dir}/game_stubs.asm")


# ---------------------------------------------------------------------------
# SMS Header Patcher
# ---------------------------------------------------------------------------

def cmd_patch_header(args):
    data = bytearray(Path(args.rom).read_bytes())
    region = REGION_CODES.get(args.region, 6) if isinstance(args.region, str) else int(args.region)
    patched = patch_sms_header(data, region)
    out_path = Path(args.out)
    out_path.write_bytes(patched)
    cs = compute_checksum(bytes(patched))
    print(f"[patch-header] Wrote {out_path} | checksum=${cs:04X} | region={region}")


# ---------------------------------------------------------------------------
# Project Scaffold Generator
# ---------------------------------------------------------------------------

def cmd_generate(args):
    out = Path(args.out)
    (out / 'hal').mkdir(parents=True, exist_ok=True)
    (out / 'stubs').mkdir(parents=True, exist_ok=True)
    (out / 'assets').mkdir(parents=True, exist_ok=True)

    manifest = json.loads(Path(args.manifest).read_text())
    prg_size = manifest.get('nes_header', {}).get('prg_size', 32768)
    rom_banks = max(8, (prg_size // 16384) + 4)  # +4 for init + vectors + assets banks

    # Copy assets if provided
    if args.assets:
        assets_src = Path(args.assets)
        for f in assets_src.iterdir():
            if f.is_file():
                import shutil
                shutil.copy(f, out / 'assets' / f.name)

    # Write all source files
    (out / 'main.asm').write_text(MAIN_ASM, encoding='utf-8')
    (out / 'memory.inc').write_text(MEMORY_INC.format(banks=rom_banks), encoding='utf-8')
    (out / 'init.asm').write_text(INIT_ASM, encoding='utf-8')
    (out / 'interrupts.asm').write_text(INTERRUPTS_ASM, encoding='utf-8')
    (out / 'assets.asm').write_text(ASSETS_ASM, encoding='utf-8')
    (out / 'hal' / 'vdp.asm').write_text(HAL_VDP_ASM, encoding='utf-8')
    (out / 'hal' / 'psg.asm').write_text(HAL_PSG_ASM, encoding='utf-8')
    (out / 'hal' / 'input.asm').write_text(HAL_INPUT_ASM, encoding='utf-8')
    (out / 'hal' / 'mapper.asm').write_text(HAL_MAPPER_ASM, encoding='utf-8')
    (out / 'stubs' / 'game_logic.asm').write_text(GAME_LOGIC_STUB_ASM, encoding='utf-8')
    write_linker_script(out, rom_banks)
    (out / 'Makefile').write_text(MAKEFILE_CONTENT, encoding='utf-8')

    print(f"[generate] SMS project scaffold written to {out}/")
    print(f"[generate] Backend: {args.backend} | ROM banks: {rom_banks}")
    print(f"[generate] Next: cd {out} && make")


# ---------------------------------------------------------------------------
# Test Runner
# ---------------------------------------------------------------------------

def cmd_test(args):
    rom = Path(args.rom)
    if not rom.exists():
        print(f"ERROR: ROM not found: {rom}", file=sys.stderr); sys.exit(1)

    report_lines = [
        f'# SMS Test Results',
        f'ROM: {rom}',
        f'Emulator: {args.emulator}',
        '',
        '## Assertions',
    ]

    # Verify SMS header
    data = rom.read_bytes()
    if len(data) >= SMS_HEADER_OFFSET_32K + 8:
        magic = data[SMS_HEADER_OFFSET_32K:SMS_HEADER_OFFSET_32K + 8]
        header_ok = magic == SMS_HEADER_MAGIC
        report_lines.append(f"- {'PASS' if header_ok else 'FAIL'} SMS header magic: {magic}")
        stored_cs = struct.unpack_from('<H', data, SMS_HEADER_OFFSET_32K + 10)[0]
        computed_cs = compute_checksum(data)
        cs_ok = stored_cs == computed_cs
        report_lines.append(f"- {'PASS' if cs_ok else 'FAIL'} Checksum: stored=${stored_cs:04X} computed=${computed_cs:04X}")
    else:
        report_lines.append("- FAIL ROM too small for header check")

    # Check INT handler location ($0038)
    if len(data) >= 0x40:
        int_byte = data[0x38]
        report_lines.append(f"- INFO Byte at $0038 (INT handler): ${int_byte:02X}")

    # Check NMI handler location ($0066)
    if len(data) >= 0x70:
        nmi_byte = data[0x66]
        report_lines.append(f"- INFO Byte at $0066 (NMI handler): ${nmi_byte:02X}")

    report_lines += [
        '',
        '## Manual Verification Required',
        '- [ ] Boot ROM in Emulicious; confirm no crash',
        '- [ ] Read VDP status $BF in INT handler (VRAM dump → check tile data)',
        '- [ ] Verify name table at VRAM $3800',
        '- [ ] Verify SAT at VRAM $3F00',
        '- [ ] Press button 1; verify game response',
        '',
        f'SHA256: {hashlib.sha256(data).hexdigest()}',
    ]

    report_path = Path(args.report)
    report_path.parent.mkdir(parents=True, exist_ok=True)
    (Path(args.report) if args.report else Path('test_results.txt')).write_text('\n'.join(report_lines), encoding='utf-8')
    print(f"[test] Report written to {report_path}")
    for line in report_lines:
        if line.startswith('- PASS') or line.startswith('- FAIL'):
            print(f"  {line}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description='NES → SMS ROM Packer & Scaffold Generator')
    sub = parser.add_subparsers(dest='cmd')

    p_gen = sub.add_parser('generate')
    p_gen.add_argument('--manifest', required=True)
    p_gen.add_argument('--assets', default=None)
    p_gen.add_argument('--backend', default='wla-dx', choices=['wla-dx', 'sdcc'])
    p_gen.add_argument('--mapper', default='sega')
    p_gen.add_argument('--out', required=True)

    p_stubs = sub.add_parser('gen-stubs')
    p_stubs.add_argument('--symbols', required=True)
    p_stubs.add_argument('--out', required=True)

    p_ph = sub.add_parser('patch-header')
    p_ph.add_argument('--rom', required=True)
    p_ph.add_argument('--region', default='6')
    p_ph.add_argument('--out', required=True)

    p_mf = sub.add_parser('write-makefile')
    p_mf.add_argument('--out', required=True)

    p_test = sub.add_parser('test')
    p_test.add_argument('--rom', required=True)
    p_test.add_argument('--emulator', default='emulicious')
    p_test.add_argument('--report', default='validation/test_results.txt')

    args = parser.parse_args()

    if args.cmd == 'generate':
        cmd_generate(args)
    elif args.cmd == 'gen-stubs':
        symbols = json.loads(Path(args.symbols).read_text())
        if isinstance(symbols, dict):
            symbols = list(symbols.values())
        gen_stubs_from_symbols(symbols, Path(args.out))
    elif args.cmd == 'patch-header':
        cmd_patch_header(args)
    elif args.cmd == 'write-makefile':
        out = Path(args.out)
        out.mkdir(parents=True, exist_ok=True)
        (out / 'Makefile').write_text(MAKEFILE_CONTENT, encoding='utf-8')
        write_linker_script(out)
        print(f"[write-makefile] Makefile + link.sms written to {out}/")
    elif args.cmd == 'test':
        cmd_test(args)
    else:
        parser.print_help()


if __name__ == '__main__':
    main()
